Repository Akshat111111/Hedging-of-Financial-Derivatives, pull requests merged in 2024-07, with the labels that each got.

#395 Create README.md
  Risk Assessment/README.md
Labels: GSSOC24, gssoc, level1

#440 Volatility Forecasting with LSTM Networks for Hedging
  Finacial Domain/Volatility Forecasting with LSTM Networks  & Mathematical model for Hedging/Mathematical Models for Volatility.docx
  Finacial Domain/Volatility Forecasting with LSTM Networks  & Mathematical model for Hedging/Volatility_Forecasting_with_LSTM_Networks_for_Hedging.ipynb
  Finacial Domain/Volatility Forecasting with LSTM Networks  & Mathematical model for Hedging/requirement.txt
  Finacial Domain/Volatility Forecasting with LSTM Networks  & Mathematical model for Hedging/volatilitydata.csv
Labels: GSSOC24, gssoc, level2

#439 Neural Network-Based Option Pricing and Hedging
  Finacial Domain/Neural Network-Based Option Pricing and Hedging/Black_Scholes_Model.docx
  Finacial Domain/Neural Network-Based Option Pricing and Hedging/NeuralNetwork_BasedOptionPricingandHedging.ipynb
  Finacial Domain/Neural Network-Based Option Pricing and Hedging/option_data (1).csv
  Finacial Domain/Neural Network-Based Option Pricing and Hedging/requirement.txt
Labels: GSSOC24, gssoc, level2

#461 Hedging with Ensemble Learning Techniques #421
  Finacial Domain/Hedging with Ensemble Learning Techniques/Hedging with Ensemble Learning Techniques.ipynb
  Finacial Domain/Hedging with Ensemble Learning Techniques/requirement.txt
  Finacial Domain/Hedging with Ensemble Learning Techniques/synthetic_market_data (1).csv
Labels: GSSOC24, gssoc, level2

#451 Solved #442- Proximity to POI
  Finacial Domain/Proximity to POI/POI.py
  Finacial Domain/Proximity to POI/pred2016l.csv
Labels: GSSOC24, gssoc, level2

#450 Delta Hedging with Support Vector Machines (SVM) #419
  Finacial Domain/Delta Hedging with Support Vector Machines (SVM)/Delta Hedging SVM Documentation.docx
  Finacial Domain/Delta Hedging with Support Vector Machines (SVM)/Delta Hedging with Support Vector Machines.ipynb
  Finacial Domain/Delta Hedging with Support Vector Machines (SVM)/deltahedgingdataset.csv
  Finacial Domain/Delta Hedging with Support Vector Machines (SVM)/requirement.txt
Labels: GSSOC24, gssoc, level2

#458 Dell Stock Prediction using lstm
  NYSE/Dell-Stock-Prediction-lstm/Data Sources/DELL_stock_action.csv
  NYSE/Dell-Stock-Prediction-lstm/Data Sources/DELL_stock_dividends.csv
  NYSE/Dell-Stock-Prediction-lstm/Data Sources/DELL_stock_history.csv
  NYSE/Dell-Stock-Prediction-lstm/Data Sources/DELL_stock_info.csv
  NYSE/Dell-Stock-Prediction-lstm/Data Sources/DELL_stock_spilts.csv
  NYSE/Dell-Stock-Prediction-lstm/dell-stock-prediction-lstm.ipynb
Labels: GSSOC24, gssoc, level2

#460 Portfolio Hedging using Generative Adversarial Networks (GANs) #420
  Finacial Domain/Portfolio Hedging using Generative Adversarial Networks (GANs)/Portfolio Hedging using Generative Adversarial Networks(GANs).ipynb
  Finacial Domain/Portfolio Hedging using Generative Adversarial Networks (GANs)/marketdata.csv
  Finacial Domain/Portfolio Hedging using Generative Adversarial Networks (GANs)/outofsamplemarketdata.csv
  Finacial Domain/Portfolio Hedging using Generative Adversarial Networks (GANs)/requirement.txt
Labels: GSSOC24, gssoc, level2

#457 HCLtech stock price prediction using Linear Regression, Support Vector Machines (SVM)
  Nifty /HCLTech Stock Analysis/Dataset/HCLTECH.csv
  Nifty /HCLTech Stock Analysis/Images/Distribution of HCLtech Daily Returns.png
  Nifty /HCLTech Stock Analysis/Images/HCLtech Bank Stock Prices with Moving Averages.png
  Nifty /HCLTech Stock Analysis/Images/HCLtech High Stock Prices.png
  Nifty /HCLTech Stock Analysis/Images/HCLtech Stock Price Clustering.png
  Nifty /HCLTech Stock Analysis/Images/HCLtech Stock Price Over Time.png
  Nifty /HCLTech Stock Analysis/Images/HCLtech Stock Price.png
  Nifty /HCLTech Stock Analysis/Model/HCLtech_stock_price_prediction_using_Linear_Regression,_Support_Vector_Machines_(SVM)_and_K_means_clustering.ipynb
  Nifty /HCLTech Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#441 Mastercard Stock Price Prediction using LSTM, SVM And K-Nearest Neighbors (KNN)
  NYSE/Mastercard Stock Analysis/Dataset/Mastercard_stock_history.csv
  NYSE/Mastercard Stock Analysis/Images/Distribution of Mastercard Daily Returns.png
  NYSE/Mastercard Stock Analysis/Images/KNN Model Stock Price Prediction.png
  NYSE/Mastercard Stock Analysis/Images/LSTM Model Stock Price Prediction.png
  NYSE/Mastercard Stock Analysis/Images/Mastercard Close Price History.png
  NYSE/Mastercard Stock Analysis/Images/Mastercard High Stock Prices.png
  NYSE/Mastercard Stock Analysis/Images/Open Stock Price of Mastercard.png
  NYSE/Mastercard Stock Analysis/Images/SVM Model Stock Price Prediction.png
  NYSE/Mastercard Stock Analysis/Model/Mastercard_Stock_Price_Prediction_using_LSTM,_SVM_And_K_Nearest_Neighbors_(KNN).ipynb
  NYSE/Mastercard Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#464 Solved #463- Predicting power consumption
  Finacial Domain/Prediction of Power Consumption/code.py
  Finacial Domain/Prediction of Power Consumption/power-laws-forecasting-energy-consumption-holidays.csv
Labels: GSSOC24, gssoc, level2

#466 Machine Learning for Risk-Neutral Density Estimation
  Finacial Domain/Machine Learning for Risk-Neutral Density Estimation/Machine Learning for Risk-Neutral Density Estimation.ipynb
  Finacial Domain/Machine Learning for Risk-Neutral Density Estimation/requirement.txt
  Finacial Domain/Machine Learning for Risk-Neutral Density Estimation/synthetic_option_data (2) (1).csv
  Finacial Domain/Machine Learning for Risk-Neutral Density Estimation/synthetic_underlying_data (1) (1).csv
Labels: GSSOC24, gssoc, level2

#467 Predictive Modeling for Exotic Options Hedging #423
  Finacial Domain/Predictive Modeling for Exotic Options Hedging/Predictive_Modeling_for_Exotic_Options_Hedging.ipynb
  Finacial Domain/Predictive Modeling for Exotic Options Hedging/requirement.txt
  Finacial Domain/Predictive Modeling for Exotic Options Hedging/synthetic_exotic_options_data (1).csv
Labels: GSSOC24, gssoc, level2

#462 Zomato Stock Price Prediction using LSTM, SVM, SGD, Decision Tree Regressor And K-Nearest Neighbors (KNN)
  Nifty /Zomato Stock Analysis/Dataset/zomato.csv
  Nifty /Zomato Stock Analysis/Images/Adj Close, High and Low Stock Prices.png
  Nifty /Zomato Stock Analysis/Images/Distribution of Zomato Daily Returns.png
  Nifty /Zomato Stock Analysis/Images/LSTM Model Stock Price Prediction.png
  Nifty /Zomato Stock Analysis/Images/Open Stock Price.png
  Nifty /Zomato Stock Analysis/Images/Zomato High Stock Prices.png
  Nifty /Zomato Stock Analysis/Images/Zomato Stock Price.png
  Nifty /Zomato Stock Analysis/Model/Zomato_Stock_Analysis.ipynb
  Nifty /Zomato Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#448 HDFC Stock Price Prediction using LSTM, K- Means Clustering And Logistic Regression
  Nifty /HDFC Stock Analysis/Dataset/HDFCBANK.NS.csv
  Nifty /HDFC Stock Analysis/Images/Distribution of HDFC Daily Returns.png
  Nifty /HDFC Stock Analysis/Images/HDFC Bank Closing Price.png
  Nifty /HDFC Stock Analysis/Images/HDFC Bank Stock Prices with Moving Averages.png
  Nifty /HDFC Stock Analysis/Images/HDFC High Stock Prices.png
  Nifty /HDFC Stock Analysis/Images/HDFC Stock Price.png
  Nifty /HDFC Stock Analysis/Images/K - Means Clustering.png
  Nifty /HDFC Stock Analysis/Images/LSTM Model.png
  Nifty /HDFC Stock Analysis/Images/XGBoost Forecast.png
  Nifty /HDFC Stock Analysis/Model/HDFC_Stock_Price_Prediction_using_LSTM,_K_Means_Clustering_And_Logistic_Regression.ipynb
  Nifty /HDFC Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#465 TCS Stock Price Prediction using LSTM, K- Means Clustering And Logistic Regression
  Nifty /TCS Stock Analysis/Dataset/TCS.csv
  Nifty /TCS Stock Analysis/Images/Distribution of TCS Daily Returns.png
  Nifty /TCS Stock Analysis/Images/K-Means Clustering of TCS Stock Price.png
  Nifty /TCS Stock Analysis/Images/TCS High Stock Prices.png
  Nifty /TCS Stock Analysis/Images/TCS Stock Price Prediction using LSTM.png
  Nifty /TCS Stock Analysis/Images/TCS Stock Price.png
  Nifty /TCS Stock Analysis/Model/TCS_Stock_Price_Prediction_using_LSTM,_K_Means_Clustering_And_Logistic_Regression.ipynb
  Nifty /TCS Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#498 Quantitative Analysis of Hedging Effectiveness using AI
  Finacial Domain/Quantitative Analysis of Hedging Effectiveness using AI/Quantitative Analysis of Hedging Effectiveness using AI .ipynb
  Finacial Domain/Quantitative Analysis of Hedging Effectiveness using AI/requirement.txt
  Finacial Domain/Quantitative Analysis of Hedging Effectiveness using AI/synthetic_hedging_data.csv
Labels: GSSOC24, gssoc, level2

#496 ONGC Stock Price Prediction using LSTM, SVM And K-Nearest Neighbors (KNN)
  Nifty /ONGC Stock Analysis/Dataset/ONGC.csv
  Nifty /ONGC Stock Analysis/Images/Screenshot 2024-07-13 191321.png
  Nifty /ONGC Stock Analysis/Images/Screenshot 2024-07-13 191329.png
  Nifty /ONGC Stock Analysis/Images/Screenshot 2024-07-13 191335.png
  Nifty /ONGC Stock Analysis/Images/Screenshot 2024-07-13 191344.png
  Nifty /ONGC Stock Analysis/Images/Screenshot 2024-07-13 191353.png
  Nifty /ONGC Stock Analysis/Images/Screenshot 2024-07-13 191401.png
  Nifty /ONGC Stock Analysis/Images/Screenshot 2024-07-13 191410.png
  Nifty /ONGC Stock Analysis/Images/Screenshot 2024-07-13 191419.png
  Nifty /ONGC Stock Analysis/Model/ONGC_Stock_Price_Prediction_using_LSTM,_SVM_And_K_Nearest_Neighbors_(KNN).ipynb
  Nifty /ONGC Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#495 Asian Paints stock Price Prediction Using LSTM, SGD And Random Forest
  Nifty /Asian Paints Stock Analysis/Dataset/ASIANPAINT.csv
  Nifty /Asian Paints Stock Analysis/Images/Asian Paints High Stock Prices.png
  Nifty /Asian Paints Stock Analysis/Images/Asian Paints Stock Price using LSTM.png
  Nifty /Asian Paints Stock Analysis/Images/Asian Paints Stock Price.png
  Nifty /Asian Paints Stock Analysis/Images/Distribution of Asian Paints Daily Returns.png
  Nifty /Asian Paints Stock Analysis/Images/SGD and Random Forest Model.png
  Nifty /Asian Paints Stock Analysis/Model/Asian_Paints_stock_Price_Prediction_using_LSTM,_SGD_And_Random_Forest.ipynb
  Nifty /Asian Paints Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#503 Titan Stock Price Prediction using Linear regression and K- Means Clustering
  Nifty /Titan Stock Analysis/Dataset/TITAN.csv
  Nifty /Titan Stock Analysis/Images/Distribution of Titan Daily Returns.png
  Nifty /Titan Stock Analysis/Images/Titan High Stock Prices.png
  Nifty /Titan Stock Analysis/Images/Titan Linear Regression.png
  Nifty /Titan Stock Analysis/Images/Titan Stock Price Clusters.png
  Nifty /Titan Stock Analysis/Images/Titan Stock Price.png
  Nifty /Titan Stock Analysis/Model/Titan_Stock_Price_Prediction_using_Linear_regression_and_K_Means_Clustering (1).ipynb
  Nifty /Titan Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#530 Britannia stock price prediction using Linear Regression, Support Vector Machines (SVM) and K means clustering
  Nifty /Britannia Stock Analysis/Dataset/BRITANNIA.csv
  Nifty /Britannia Stock Analysis/Images/Screenshot 2024-07-16 190023.png
  Nifty /Britannia Stock Analysis/Images/Screenshot 2024-07-16 190034.png
  Nifty /Britannia Stock Analysis/Images/Screenshot 2024-07-16 190041.png
  Nifty /Britannia Stock Analysis/Images/Screenshot 2024-07-16 190050.png
  Nifty /Britannia Stock Analysis/Images/Screenshot 2024-07-16 190056.png
  Nifty /Britannia Stock Analysis/Images/Screenshot 2024-07-16 190102.png
  Nifty /Britannia Stock Analysis/Images/Screenshot 2024-07-16 190110.png
  Nifty /Britannia Stock Analysis/Model/Britannia_stock_price_prediction_using_Linear_Regression,_Support_Vector_Machines_(SVM)_and_K_means_clustering.ipynb
  Nifty /Britannia Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#499 Wipro Stock Price Prediction using LSTM, SVR, KNN
  Nifty /Wipro Stock Analysis/Dataset/WIPRO.csv
  Nifty /Wipro Stock Analysis/Images/Disrtibution of wipro.png
  Nifty /Wipro Stock Analysis/Images/KNN.png
  Nifty /Wipro Stock Analysis/Images/LSTM.png
  Nifty /Wipro Stock Analysis/Images/SVR.png
  Nifty /Wipro Stock Analysis/Images/Wipro High Stock Prices.png
  Nifty /Wipro Stock Analysis/Images/Wipro Stock Price.png
  Nifty /Wipro Stock Analysis/Model/Wipro_Stock_Price_Prediction_using_LSTM,_SVR,_KNN.ipynb
  Nifty /Wipro Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#526 Graph Neural Networks for Network-Based Hedging
  Finacial Domain/Graph Neural Networks for Network-Based Hedging/Graph_Neural_Networks_for_Network_Based_Hedging.ipynb
  Finacial Domain/Graph Neural Networks for Network-Based Hedging/requirement.txt
  Finacial Domain/Graph Neural Networks for Network-Based Hedging/synthetic_market_data (1).csv
Labels: GSSOC24, gssoc, level2

#509 Solved #491
  Finacial Domain/Predicting insider trading activities/code.py
  Finacial Domain/Predicting insider trading activities/sd254_users.csv
Labels: GSSOC24, gssoc, level2

#534 PortFolio Optimaization Using Genetic ALgorithm added
  Finacial Domain/PortFolio Optimaization Using Genetic ALgorithm/Portfolio_Optimization_Using_Genetic_Algorithm.ipynb
  Finacial Domain/PortFolio Optimaization Using Genetic ALgorithm/portfolio_data.csv
  Finacial Domain/PortFolio Optimaization Using Genetic ALgorithm/readme.md
Labels: GSSOC24, gssoc, level2

#537 Market Making and Liquidity Provision Using RL added
  Finacial Domain/Market Making and Liquidity Provision Using RL/Market_MakingAndLiquidityProvision.ipynb
  Finacial Domain/Market Making and Liquidity Provision Using RL/market_data.csv
  Finacial Domain/Market Making and Liquidity Provision Using RL/readme.md
  Finacial Domain/Market Making and Liquidity Provision Using RL/requirement.txt
Labels: GSSOC24, gssoc, level2

#555 JSW Steel stock price prediction
  Nifty /JSW Steel Stock Analysis/Dataset/JSWSTEEL.csv
  Nifty /JSW Steel Stock Analysis/Images/Screenshot 2024-07-18 134856.png
  Nifty /JSW Steel Stock Analysis/Images/Screenshot 2024-07-18 134946.png
  Nifty /JSW Steel Stock Analysis/Images/Screenshot 2024-07-18 134954.png
  Nifty /JSW Steel Stock Analysis/Images/Screenshot 2024-07-18 135007.png
  Nifty /JSW Steel Stock Analysis/Images/Screenshot 2024-07-18 135015.png
  Nifty /JSW Steel Stock Analysis/Images/Screenshot 2024-07-18 135023.png
  Nifty /JSW Steel Stock Analysis/Model/JSW_Steel_Stock.ipynb
  Nifty /JSW Steel Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#556 Power Grid Stock Price Prediction
  Nifty /Power Grid Stock Analysis/Dataset/POWERGRID.csv
  Nifty /Power Grid Stock Analysis/Images/Screenshot 2024-07-18 143050.png
  Nifty /Power Grid Stock Analysis/Images/Screenshot 2024-07-18 143059.png
  Nifty /Power Grid Stock Analysis/Images/Screenshot 2024-07-18 143108.png
  Nifty /Power Grid Stock Analysis/Images/Screenshot 2024-07-18 143117.png
  Nifty /Power Grid Stock Analysis/Images/Screenshot 2024-07-18 143123.png
  Nifty /Power Grid Stock Analysis/Images/Screenshot 2024-07-18 143130.png
  Nifty /Power Grid Stock Analysis/Model/Power_Grid_Stock_Price_Prediction_using_LSTM,_SVM_and_K_Nearest_Neighbors_(KNN).ipynb
  Nifty /Power Grid Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#510 Added GDP prediction
  Finacial Domain/GDP Prediction/Readme.md
  Finacial Domain/GDP Prediction/gdp_prediction_model.ipynb
  Finacial Domain/GDP Prediction/world.csv
Labels: GSSOC24, gssoc, level2

#513 here is my analysis
  NYSE/Visualizing USA Stocks/.ipynb_checkpoints/visualizing-usa-stocks-checkpoint.ipynb
  NYSE/Visualizing USA Stocks/visualizing-usa-stocks.ipynb
Labels: GSSOC24, gssoc, level2

#523 here is my stock prediction of NVDA
  NYSE/NVDA stock prediction/.ipynb_checkpoints/nvda-stocks-prediction-checkpoint.ipynb
  NYSE/NVDA stock prediction/NVDA.csv
  NYSE/NVDA stock prediction/nvda-stocks-prediction.ipynb
Labels: GSSOC24, gssoc, level2

#525 here is my Uber stock prediction
  NYSE/Uber stock prediction /UBER.csv
  NYSE/Uber stock prediction /uber stock prediction lstm.ipynb
Labels: GSSOC24, gssoc, level2

#528 added AR, MA, ARMA model
  Time Series Analysis Models/Images/AR(1) Model.png
  Time Series Analysis Models/Images/ARMA Model.png
  Time Series Analysis Models/Images/MA Model.png
  Time Series Analysis Models/README.md
  Time Series Analysis Models/stats-models-ar-ma-arma.ipynb
Labels: GSSOC24, gssoc, level2

#573 Algorithmic_Trading_Strategy_Optimization_Using_Genetic_Algorithms added
  Finacial Domain/Algorithmic_Trading_Strategy_Optimization_Using_Genetic_Algorithms/Algorithmic_Trading_Strategy_Optimization_Using_Genetic_Algorithms (1).ipynb
  Finacial Domain/Algorithmic_Trading_Strategy_Optimization_Using_Genetic_Algorithms/readme.md
  Finacial Domain/Algorithmic_Trading_Strategy_Optimization_Using_Genetic_Algorithms/trading_data.csv
Labels: GSSOC24, gssoc, level2

#588 Added Loan Repayment Prediction
  Loan Status Prediction/Loan Repayment Prediction/Loan_Repayment_Prediction.ipynb
  Loan Status Prediction/Loan Repayment Prediction/Readme.md
  Loan Status Prediction/Loan Repayment Prediction/loan_data.csv
Labels: GSSOC24, gssoc, level2

#581 Added Bank Loan Approval Prediction
  Loan Status Prediction/Bank Loan Approval Prediction/Dataset/UniversalBank.csv
  Loan Status Prediction/Bank Loan Approval Prediction/Images/Age Distribution.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/Age.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/Approved_Not_Approved.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/Average CC Spending.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/Box Plot of income.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/CCAvg Distribution by Personal Loan.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/Distribution of Education.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/FNN_Accuracy.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/FNN_Loss.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/Heatmap.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/Mortgage Distribution by Personal Loan.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/Personal loans.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/TabNet_Accuracy.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/TabNet_Loss.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/Updated_Correlation_Matrix.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/WDNN_Accuracy.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/WDNN_Loss.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/bar graph.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/conf_matrix.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/confusion matrix.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/histogram.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/income.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/input visualisation.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/modelloss.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/pie chart.png
  Loan Status Prediction/Bank Loan Approval Prediction/Images/training loss.png
  Loan Status Prediction/Bank Loan Approval Prediction/Model/FNN_TabNet_WDNN.ipynb
  Loan Status Prediction/Bank Loan Approval Prediction/Model/README.md
  Loan Status Prediction/Bank Loan Approval Prediction/Model/bank-loan-approval-using-AI.ipynb
  Loan Status Prediction/Bank Loan Approval Prediction/README.md
  Loan Status Prediction/Bank Loan Approval Prediction/requirements.txt
Labels: GSSOC24, gssoc, level3

#574 Blockchain_and_Cryptography_Investment_Strategy added
  Finacial Domain/Blockchain_and_Cryptography_Investment_Strategy/Blockchain_and_Cryptocurrency_Investment_Strategies.ipynb
  Finacial Domain/Blockchain_and_Cryptography_Investment_Strategy/crypto_investment_data.csv
  Finacial Domain/Blockchain_and_Cryptography_Investment_Strategy/readme.md
Labels: GSSOC24, gssoc, level2

#576 Stress testing financial portfolio added
  Finacial Domain/Stress testing financial portfolio/Stress_Testing_Financial_Portfolios_with_RL.ipynb
  Finacial Domain/Stress testing financial portfolio/portfolio_data.csv
  Finacial Domain/Stress testing financial portfolio/readme.md
Labels: GSSOC24, gssoc, level2

#582 Added Fraudulent Transactions Detection
  Credit Risk/Fraudulent Transactions Detection/Dataset/README.md
  Credit Risk/Fraudulent Transactions Detection/Images/Dataset head.png
  Credit Risk/Fraudulent Transactions Detection/Images/acc_com_lr_rfc.png
  Credit Risk/Fraudulent Transactions Detection/Images/lr_cm.png
  Credit Risk/Fraudulent Transactions Detection/Images/rfc_cm.png
  Credit Risk/Fraudulent Transactions Detection/Model/README.md
  Credit Risk/Fraudulent Transactions Detection/Model/fraud_transaction_detection.ipynb
  Credit Risk/Fraudulent Transactions Detection/Model/kaggle.json
  Credit Risk/Fraudulent Transactions Detection/requirement.txt
Labels: GSSOC24, gssoc, level2

#578 Currency Arbitrage with Reinforcement Learning added
  Finacial Domain/Currency Arbitrage with Reinforcement Learning/agent_for_currency_arbitrage_using_Rlearning.ipynb
  Finacial Domain/Currency Arbitrage with Reinforcement Learning/currency_data.csv
  Finacial Domain/Currency Arbitrage with Reinforcement Learning/readme.md
Labels: GSSOC24, gssoc, level2

#579 Dynamic Hedging Strategies using Reinforcement Learning added
  Finacial Domain/Dynamic Hedging Strategies using Reinforcement Learning/Dynamic_Hedging_StrategiesReinforcementLear.ipynb
  Finacial Domain/Dynamic Hedging Strategies using Reinforcement Learning/dqn_agent.h5
  Finacial Domain/Dynamic Hedging Strategies using Reinforcement Learning/readme.md
  Finacial Domain/Dynamic Hedging Strategies using Reinforcement Learning/requirement.txt
Labels: GSSOC24, gssoc, level2

#477 Added salary prediction using Machine learning
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/app.py
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/images/actual_Vs_predicted_lr.png
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/images/actual_vs_predicted_gbm.png
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/images/actual_vs_predicted_rf.png
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/images/actual_vs_predicted_xgboost.png
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/images/box_plot_gender.png
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/images/count_plot_job_titles.png
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/images/histogram.png
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/images/model_comparison.png
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/images/r2_square_value_cross_validation.png
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/images/salary_distribution_education_level_viiolin_plot.png
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/images/scatter_plot_year_of_Experience.png
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/readme.md
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/requirements.txt
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/salary_prediction.ipynb
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/salary_prediction_data.csv
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/salary_prediction_model.pkl
  Loan Status Prediction/Human Resource  Analysis/salary_prediction_using_ML/webapp.mp4
Labels: GSSOC24, gssoc, level3

#527 Loan interest rate prediction using machine learning
  Loan Status Prediction/Loan_interest_rate_prediction/app.py
  Loan Status Prediction/Loan_interest_rate_prediction/images/annual_income_distri.png
  Loan Status Prediction/Loan_interest_rate_prediction/images/box_plot.png
  Loan Status Prediction/Loan_interest_rate_prediction/images/count_plot-1.png
  Loan Status Prediction/Loan_interest_rate_prediction/images/debt_to_income_violin_plot.png
  Loan Status Prediction/Loan_interest_rate_prediction/images/gbm_actual_vs_predicted.png
  Loan Status Prediction/Loan_interest_rate_prediction/images/gender_distribution_count_plot.png
  Loan Status Prediction/Loan_interest_rate_prediction/images/heatmap.png
  Loan Status Prediction/Loan_interest_rate_prediction/images/lr_actualvspredicted.png
  Loan Status Prediction/Loan_interest_rate_prediction/images/pair_plot.png
  Loan Status Prediction/Loan_interest_rate_prediction/images/pie_chart.png
  Loan Status Prediction/Loan_interest_rate_prediction/images/reason_for_Loan.png
  Loan Status Prediction/Loan_interest_rate_prediction/images/rf_actual_vs_predicted.png
  Loan Status Prediction/Loan_interest_rate_prediction/images/xgboost_actual_vs_predicted.png
  Loan Status Prediction/Loan_interest_rate_prediction/loan_interest_prediction.ipynb
  Loan Status Prediction/Loan_interest_rate_prediction/readme.md
  Loan Status Prediction/Loan_interest_rate_prediction/requirements.txt
  Loan Status Prediction/Loan_interest_rate_prediction/webapp.mp4
  Loan Status Prediction/Loan_interest_rate_prediction/xgboost_model.pkl
Labels: GSSOC24, gssoc, level3

#583 UltraTech Cement Ltd Stock Price Prediction using LSTM, SVR, KNN and K Means Clustering
  Nifty /UltraTech Cement Ltd Stock Analysis/Dataset/ULTRACEMCO.csv
  Nifty /UltraTech Cement Ltd Stock Analysis/Images/Screenshot 2024-07-18 212826.png
  Nifty /UltraTech Cement Ltd Stock Analysis/Images/Screenshot 2024-07-18 212835.png
  Nifty /UltraTech Cement Ltd Stock Analysis/Images/Screenshot 2024-07-18 212843.png
  Nifty /UltraTech Cement Ltd Stock Analysis/Images/Screenshot 2024-07-18 212852.png
  Nifty /UltraTech Cement Ltd Stock Analysis/Images/Screenshot 2024-07-18 212910.png
  Nifty /UltraTech Cement Ltd Stock Analysis/Images/Screenshot 2024-07-18 212934.png
  Nifty /UltraTech Cement Ltd Stock Analysis/Images/Screenshot 2024-07-18 213006.png
  Nifty /UltraTech Cement Ltd Stock Analysis/Model/UltraTech_Cement_Ltd_Stock_Price_Prediction_using_LSTM,_SVR,_KNN_and_K_Means_Clustering.ipynb
  Nifty /UltraTech Cement Ltd Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#585 Here is my zoom eda
  NYSE/ZOOM stock EDA/.ipynb_checkpoints/eda zoom stocks prices-checkpoint.ipynb
  NYSE/ZOOM stock EDA/Zoom.csv
  NYSE/ZOOM stock EDA/eda zoom stocks prices.ipynb
Labels: GSSOC24, gssoc, level2

#589 here is my AMD stock prediction
  NYSE/AMD stock prediction/.ipynb_checkpoints/AMD by LSTM-checkpoint.ipynb
  NYSE/AMD stock prediction/AMD by LSTM.ipynb
  NYSE/AMD stock prediction/AMD.csv
Labels: GSSOC24, gssoc, level2

#590 here is my Oracle stock prediction
  NYSE/Oracle stock prediction/.ipynb_checkpoints/oracle by LSTM-checkpoint.ipynb
  NYSE/Oracle stock prediction/Oracle.csv
  NYSE/Oracle stock prediction/oracle by LSTM.ipynb
Labels: GSSOC24, gssoc, level2

#593 Explainable AI for Transparent Hedging Decisions #472
  Finacial Domain/Explainable AI for Transparent Hedging Decisions/Explainable_AI_for_Transparent_Hedging_Decisions.ipynb
  Finacial Domain/Explainable AI for Transparent Hedging Decisions/dataset.csv
  Finacial Domain/Explainable AI for Transparent Hedging Decisions/requirement.txt
Labels: GSSOC24, gssoc, level2

#594 Hedging Cryptocurrencies with Reinforcement Learning #473
  Finacial Domain/Hedging Cryptocurrencies with Reinforcement Learning/Hedging Cryptocurrencies with Reinforcement Learning.ipynb
  Finacial Domain/Hedging Cryptocurrencies with Reinforcement Learning/crypto_price_data.csv
  Finacial Domain/Hedging Cryptocurrencies with Reinforcement Learning/requirement.txt
Labels: GSSOC24, gssoc, level2

#595 Meta-Learning for Adaptive Hedging Strategies #474
  Finacial Domain/Meta-Learning for Adaptive Hedging Strategies/Meta-Learning for Adaptive Hedging Strategies.ipynb
  Finacial Domain/Meta-Learning for Adaptive Hedging Strategies/requrement.txt
Labels: GSSOC24, gssoc, level2

#596 here is my EA stock prediction
  NYSE/EA (Electronic Arts) Stocks/.ipynb_checkpoints/EA-checkpoint.ipynb
  NYSE/EA (Electronic Arts) Stocks/EA.csv
  NYSE/EA (Electronic Arts) Stocks/EA.ipynb
Labels: GSSOC24, gssoc, level2

#598 here is my Reddit stock
  NYSE/Reddit stocks/.ipynb_checkpoints/Reddit by LSTM-checkpoint.ipynb
  NYSE/Reddit stocks/Reddit by LSTM.ipynb
  NYSE/Reddit stocks/stocks.csv
Labels: GSSOC24, gssoc, level2

#599 here is my Robinhood stock
  NYSE/Robinhood Stock Prediction/HOOD.csv
  NYSE/Robinhood Stock Prediction/hood-metrics.ipynb
Labels: GSSOC24, gssoc, level2

#600 here is my Nasdaq
  NYSE/Nasdaq stock forecasting/.ipynb_checkpoints/nasdaq stock forecasting-checkpoint.ipynb
  NYSE/Nasdaq stock forecasting/IKNA.csv
  NYSE/Nasdaq stock forecasting/nasdaq stock forecasting.ipynb
Labels: GSSOC24, gssoc, level2

#603 Added Payment Fraud Detection
  Credit Risk/Payment Fraud Detection/Dataset.md
  Credit Risk/Payment Fraud Detection/Images/Correlation Matrix.png
  Credit Risk/Payment Fraud Detection/Images/Count of all type of transaction.png
  Credit Risk/Payment Fraud Detection/Images/Count of frauds.png
  Credit Risk/Payment Fraud Detection/Images/Number of transaction by Type of transaction and isFlaggedFraud.png
  Credit Risk/Payment Fraud Detection/Images/Number of transaction by Type of transaction and isFraud.png
  Credit Risk/Payment Fraud Detection/Model/Payments Fraud Detection using DL.ipynb
  Credit Risk/Payment Fraud Detection/Model/README.md
  Credit Risk/Payment Fraud Detection/Model/RNN_LSTM.model
  Credit Risk/Payment Fraud Detection/Model/multiple_input_neural_network.model
  Credit Risk/Payment Fraud Detection/Model/single_input_neural_network.model
  Credit Risk/Payment Fraud Detection/requirements.txt
Labels: GSSOC24, gssoc, level3

#638 Create interest_model.py
  Loan Status Prediction/interest_model.py
Labels: GSSOC24, gssoc, level2

#630 Added Startup_Profit_Prediction
  Startup_Profit_Prediction/50_Startups.csv
  Startup_Profit_Prediction/Readme.md
  Startup_Profit_Prediction/Startup_Profit_Prediction.ipynb
Labels: GSSOC24, gssoc, level2

#610 Credit Risk Modeling Added
  Credit Risk/Credit Risk Modeling/credit_data.csv
  Credit Risk/Credit Risk Modeling/genetic_algorithm_on_Credit_Risk_Modeling_.ipynb
  Credit Risk/Credit Risk Modeling/readme.md
Labels: GSSOC24, gssoc, level2

#612 Cross_asset_Hedging added
  Finacial Domain/Cross_asset_Hedging/Cross_asset_Hedging.ipynb
  Finacial Domain/Cross_asset_Hedging/readme.md
  Finacial Domain/Cross_asset_Hedging/requirement.txt
Labels: GSSOC24, gssoc, level2

#613 Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms added
  Finacial Domain/Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms/Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms.ipynb
  Finacial Domain/Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms/readme.md
  Finacial Domain/Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms/requirement.txt
Labels: GSSOC24, gssoc, level2

#629 Predicting Corporate Earnings Using Deep Learning added
  Finacial Domain/Predicting Corporate Earnings Using Deep Learning/Predicting_Corporate_Earnings_Using_Deep_Learning.ipynb
  Finacial Domain/Predicting Corporate Earnings Using Deep Learning/corporate_earnings_prediction.csv
  Finacial Domain/Predicting Corporate Earnings Using Deep Learning/readme.md
Labels: GSSOC24, gssoc, level2

#584 here is my model of fang
  NYSE/FAANG stocks /eda visualization of fang.ipynb
  NYSE/FAANG stocks /faang_stocks_pandemic_data.csv
Labels: GSSOC24, gssoc, level3

#586 Here is my intel prediction
  NYSE/Intel stocks EDA/.ipynb_checkpoints/Intel stocks EDA and prediction-checkpoint.ipynb
  NYSE/Intel stocks EDA/Intel.csv
  NYSE/Intel stocks EDA/intel stocks EDA and prediction.ipynb
Labels: GSSOC24, gssoc, level2

#617 Time Series Analysis Models Addition : ARIMA, SARIMA
  Time Series Analysis Models/Images/ARIMA Model.png
  Time Series Analysis Models/Images/SARIMA Model.png
  Time Series Analysis Models/README.md
  Time Series Analysis Models/stats-models-arima-sarima.ipynb
Labels: GSSOC24, gssoc, level3

#631 Market Basket Analysis
  Finacial Domain/Market Basket Analysis/Dataset/basket_analysis.csv
  Finacial Domain/Market Basket Analysis/Images/Association Rules - Apriori.png
  Finacial Domain/Market Basket Analysis/Images/Association Rules - FP Growth.png
  Finacial Domain/Market Basket Analysis/Images/Comparison Results.png
  Finacial Domain/Market Basket Analysis/Images/Comparison.png
  Finacial Domain/Market Basket Analysis/Images/Dataset.png
  Finacial Domain/Market Basket Analysis/Model/Market_Basket_Analysis.ipynb
  Finacial Domain/Market Basket Analysis/Model/market_basket_analysis.py
  Finacial Domain/Market Basket Analysis/README.md
  Finacial Domain/Market Basket Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#649 Interest Rate Swap Optimization added
  Finacial Domain/Interest Rate Swap Optimization/Interest_Rate_Swap_Optimization.ipynb
  Finacial Domain/Interest Rate Swap Optimization/interest_rate_swap_data.csv
  Finacial Domain/Interest Rate Swap Optimization/readme.md
Labels: GSSOC24, gssoc, level2

#650 here is my all indians banks EDA and prediction
  Nifty /Nifty of history of INDIAN Banks/.DS_Store
  Nifty /Nifty of history of INDIAN Banks/.ipynb_checkpoints/nifity-checkpoint.ipynb
  Nifty /Nifty of history of INDIAN Banks/AUBANK.NS_data.csv
  Nifty /Nifty of history of INDIAN Banks/AXISBANK.NS_data.csv
  Nifty /Nifty of history of INDIAN Banks/BANDHANBNK.NS_data.csv
  Nifty /Nifty of history of INDIAN Banks/BANKBARODA.NS_data.csv
  Nifty /Nifty of history of INDIAN Banks/FEDERALBNK.NS_data.csv
  Nifty /Nifty of history of INDIAN Banks/HDFCBANK.NS_data.csv
  Nifty /Nifty of history of INDIAN Banks/ICICIBANK.NS_data.csv
  Nifty /Nifty of history of INDIAN Banks/IDFCFIRSTB.NS_data.csv
  Nifty /Nifty of history of INDIAN Banks/INDUSINDBK.NS_data.csv
  Nifty /Nifty of history of INDIAN Banks/KOTAKBANK.NS_data.csv
  Nifty /Nifty of history of INDIAN Banks/NSEBANK_data.csv
  Nifty /Nifty of history of INDIAN Banks/PNB.NS_data.csv
  Nifty /Nifty of history of INDIAN Banks/SBIN.NS_data.csv
  Nifty /Nifty of history of INDIAN Banks/nifity.ipynb
Labels: GSSOC24, gssoc, level2

#633 Bharti Airtel Stock Price Prediction Using LSTM, SVM, KNN and XGBoost
  Nifty /Bharti Airtel Stock Analysis/Dataset/BHARTIARTL.csv
  Nifty /Bharti Airtel Stock Analysis/Images/Screenshot 2024-07-24 172255.png
  Nifty /Bharti Airtel Stock Analysis/Images/Screenshot 2024-07-24 172305.png
  Nifty /Bharti Airtel Stock Analysis/Images/Screenshot 2024-07-24 172311.png
  Nifty /Bharti Airtel Stock Analysis/Images/Screenshot 2024-07-24 172320.png
  Nifty /Bharti Airtel Stock Analysis/Images/Screenshot 2024-07-24 172330.png
  Nifty /Bharti Airtel Stock Analysis/Model/Bharti_Airtel_Stock_Price_Prediction_Using_LSTM,_SVM,_KNN_and_XGBoost.ipynb
  Nifty /Bharti Airtel Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#637 Create data_cleaning.py
  Loan Status Prediction/data_cleaning.py
Labels: GSSOC24, gssoc, level2

#577 Added restaurant revenue prediction using machine learning
  Webapp/Loan Web App/app.py
  Webapp/Loan Web App/gitignore.txt
  Webapp/Loan Web App/model.pkl
  Webapp/Loan Web App/readme.md
  Webapp/Loan Web App/sample.mp4
  Webapp/Loan Web App/utils.py
  Webapp/Restaurant_revenue_prediction/INDHOTEL.NS.csv
  Webapp/Restaurant_revenue_prediction/app.py
  Webapp/Restaurant_revenue_prediction/images/actual_vs_predicted.png
  Webapp/Restaurant_revenue_prediction/images/actual_vs_predicted_dt.png
  Webapp/Restaurant_revenue_prediction/images/actual_vs_predicted_rf.png
  Webapp/Restaurant_revenue_prediction/images/actual_vs_predicted_xgboost.png
  Webapp/Restaurant_revenue_prediction/images/average_meal_prices_histogram.png
  Webapp/Restaurant_revenue_prediction/images/boxplot.png
  Webapp/Restaurant_revenue_prediction/images/boxplot_processed.png
  Webapp/Restaurant_revenue_prediction/images/correaltion_heamap.png
  Webapp/Restaurant_revenue_prediction/images/count_plot.png
  Webapp/Restaurant_revenue_prediction/images/count_plot_of_r_squared.png
  Webapp/Restaurant_revenue_prediction/images/hexbin_plot.png
  Webapp/Restaurant_revenue_prediction/images/histogram.png
  Webapp/Restaurant_revenue_prediction/images/histogram_service_quality.png
  Webapp/Restaurant_revenue_prediction/images/log_tranformation.png
  Webapp/Restaurant_revenue_prediction/images/pie_chart.png
  Webapp/Restaurant_revenue_prediction/images/revenue_vs_marketig_budget.png
  Webapp/Restaurant_revenue_prediction/images/skewness.png
  Webapp/Restaurant_revenue_prediction/images/social_media_followers_vs_restaurant_location.png
  Webapp/Restaurant_revenue_prediction/images/violin_plot.png
  Webapp/Restaurant_revenue_prediction/images/weekday_weekend_location.png
  Webapp/Restaurant_revenue_prediction/indian_hotels_stocks_analysis.ipynb
  Webapp/Restaurant_revenue_prediction/readme.md
  Webapp/Restaurant_revenue_prediction/requirements.txt
  Webapp/Restaurant_revenue_prediction/restaurant_data.csv
  Webapp/Restaurant_revenue_prediction/restaurant_revenue_prediction.ipynb
  Webapp/Restaurant_revenue_prediction/webapp.mp4
Labels: GSSOC24, gssoc, level3

#592 here is my sony stock prediction
  NYSE/Sony stock prediction/.ipynb_checkpoints/Sony by LSTM-checkpoint.ipynb
  NYSE/Sony stock prediction/SONY.csv
  NYSE/Sony stock prediction/Sony by LSTM.ipynb
Labels: GSSOC24, gssoc, level2

#646 Store Sales Prediction
  Hedging with Real Estate/Store Sales Prediction/Dataset/Dataset.md
  Hedging with Real Estate/Store Sales Prediction/Images/Screenshot (297).png
  Hedging with Real Estate/Store Sales Prediction/Images/Screenshot (298).png
  Hedging with Real Estate/Store Sales Prediction/Images/Screenshot (299).png
  Hedging with Real Estate/Store Sales Prediction/Images/Screenshot (303).png
  Hedging with Real Estate/Store Sales Prediction/Model/eda-for-sales.ipynb
  Hedging with Real Estate/Store Sales Prediction/Model/ml-store-sales.ipynb
  Hedging with Real Estate/Store Sales Prediction/Model/store-sales-rnn.ipynb
  Hedging with Real Estate/Store Sales Prediction/README.md
  Hedging with Real Estate/Store Sales Prediction/Requirement.txt
Labels: GSSOC24, gssoc, level3

#648 optimized the trading strategy based on sentiment analysis added
  Finacial Domain/optimized the trading strategy based on sentiment analysis/optimized_the_trading_strategy_based_on_sentiment_analysis.ipynb
  Finacial Domain/optimized the trading strategy based on sentiment analysis/readme.md
  Finacial Domain/optimized the trading strategy based on sentiment analysis/sentiment_trading_data.csv
Labels: GSSOC24, gssoc, level2

#655 Deep Learning for Economic Indicator Forecasting added
  Finacial Domain/Deep Learning for Economic Indicator Forecasting/Deep_Learning_for_Economic_Indicator_Forecasting.ipynb
  Finacial Domain/Deep Learning for Economic Indicator Forecasting/economic_indicator_data.csv
  Finacial Domain/Deep Learning for Economic Indicator Forecasting/readme.md
  Finacial Domain/Deep Learning for Economic Indicator Forecasting/requirement.txt
Labels: GSSOC24, gssoc, level2

#712 predicting Real Estate Prices Using Deep Learning added
  Hedging with Real Estate/predicting Real Estate Prices Using Deep Learning/Financial_Time_Series_Forecasting_with_LSTM.ipynb
  Hedging with Real Estate/predicting Real Estate Prices Using Deep Learning/readme.md
  Hedging with Real Estate/predicting Real Estate Prices Using Deep Learning/real_estate_prices.csv
  Hedging with Real Estate/predicting Real Estate Prices Using Deep Learning/requirement.txt
Labels: GSSOC24, gssoc, level2

#656 Predicting Commodity Prices Using Deep Learning
  Finacial Domain/Predicting Commodity Prices Using Deep Learning/Predicting_Commodity_Prices_Using_Deep_Learning.ipynb
  Finacial Domain/Predicting Commodity Prices Using Deep Learning/readme.md
  Finacial Domain/Predicting Commodity Prices Using Deep Learning/requirement.txt
  Finacial Domain/Predicting Commodity Prices Using Deep Learning/synthetic_commodity_price_data.csv
Labels: GSSOC24, gssoc, level2

#657 Predicting Interest Rate Movements Using Deep Learning added
  Finacial Domain/Predicting Interest Rate Movements Using Deep Learning/Predicting_Interest_Rate_Movements_Using_Deep_Learning.ipynb
  Finacial Domain/Predicting Interest Rate Movements Using Deep Learning/readme.md
  Finacial Domain/Predicting Interest Rate Movements Using Deep Learning/requirement.txt
  Finacial Domain/Predicting Interest Rate Movements Using Deep Learning/synthetic_interest_rate_data.csv
Labels: GSSOC24, gssoc, level2

#678 Predictive Maintenance for Financial Services Infrastructure added
  Finacial Domain/Predictive Maintenance for Financial Services Infrastructure/Predictive_Maintenance_for_financial_Services_infrastructure.ipynb
  Finacial Domain/Predictive Maintenance for Financial Services Infrastructure/predictive_maintenance_data.csv
  Finacial Domain/Predictive Maintenance for Financial Services Infrastructure/readme.md
Labels: GSSOC24, gssoc, level2

#679 Pension Fund Optimization added
  Finacial Domain/Pension Fund Optimization/PensionFundOptimization.ipynb
  Finacial Domain/Pension Fund Optimization/pension_fund_data.csv
  Finacial Domain/Pension Fund Optimization/readme.md
Labels: GSSOC24, gssoc, level2

#683 added Credit Risk and Scorecard evaluation
  Credit Risk/ScoreCard Evaluation/Dataset/README.md
  Credit Risk/ScoreCard Evaluation/Models/development-of-credit-risk-model-scorecard.ipynb
Labels: GSSOC24, gssoc, level2

#680 Optimal Tax Strategy Development added
  Finacial Domain/Optimal Tax Strategy Development/TaxStrategyDeeplearning_algorithm.ipynb
  Finacial Domain/Optimal Tax Strategy Development/readme.md
  Finacial Domain/Optimal Tax Strategy Development/synthetic_tax_strategy_data.csv
Labels: GSSOC24, gssoc, level2

#681 Insurance Claim Prediction added
  Finacial Domain/Insurance Claim Prediction/Insurance_Claim_Prediction.ipynb
  Finacial Domain/Insurance Claim Prediction/insurance_claim_data.csv
  Finacial Domain/Insurance Claim Prediction/readme.md
Labels: GSSOC24, gssoc, level2

#682 Smart Financial Advisory added
  Finacial Domain/Smart Financial Advisory/Smart_Financial_Advisory.ipynb
  Finacial Domain/Smart Financial Advisory/financial_advisory_dataset.csv
  Finacial Domain/Smart Financial Advisory/readme.md
  Finacial Domain/Smart Financial Advisory/requirement.txt
Labels: GSSOC24, gssoc, level2

#618 here is my AIrtel stock prediction
  Nifty /Airtel stock prediction /.ipynb_checkpoints/bharti-airtel-price-prediction-checkpoint.ipynb
  Nifty /Airtel stock prediction /BhartiAirtel.csv
  Nifty /Airtel stock prediction /bharti-airtel-price-prediction.ipynb
Labels: GSSOC24, gssoc, level2

#601 HERE si my TCS stock preddition by using LSTM
  Nifty /TCS Stock Analysis/TCS stocks by LSTM/.ipynb_checkpoints/TCS by LSTM-checkpoint.ipynb
  Nifty /TCS Stock Analysis/TCS stocks by LSTM/.ipynb_checkpoints/tcs stock prediction pycaret-checkpoint.ipynb
  Nifty /TCS Stock Analysis/TCS stocks by LSTM/TCS by LSTM.ipynb
  Nifty /TCS Stock Analysis/TCS stocks by LSTM/TCS_stock_action.csv
  Nifty /TCS Stock Analysis/TCS stocks by LSTM/TCS_stock_history.csv
  Nifty /TCS Stock Analysis/TCS stocks by LSTM/TCS_stock_info.csv
  Nifty /TCS Stock Analysis/TCS stocks by LSTM/logs.log
Labels: GSSOC24, gssoc, level2

#684 Here is my Nifity EDA
  Nifty /EDA Stock Market Index Data India (1990 - 2022)/.ipynb_checkpoints/eda-stock-market-index-data-india-1990-2022-checkpoint.ipynb
  Nifty /EDA Stock Market Index Data India (1990 - 2022)/NIFTY 100 - HistoricalPE_PBDIV_Data .csv
  Nifty /EDA Stock Market Index Data India (1990 - 2022)/NIFTY 50_Data.csv
  Nifty /EDA Stock Market Index Data India (1990 - 2022)/eda-stock-market-index-data-india-1990-2022.ipynb
Labels: GSSOC24, gssoc, level2

#688 here is my Saudi real state prediction
  Hedging with Real Estate/Saudi real state /Saudi Arabia Real Estate (AQAR)/.ipynb_checkpoints/Saudi-house-price-checkpoint.ipynb
  Hedging with Real Estate/Saudi real state /Saudi Arabia Real Estate (AQAR)/SA_Aqar.csv
  Hedging with Real Estate/Saudi real state /Saudi Arabia Real Estate (AQAR)/Saudi-house-price.ipynb
  Hedging with Real Estate/Saudi real state /Saudi Arabia Real Estate (AQAR)/pipe_dt_model.pkl
Labels: GSSOC24, gssoc, level2

#689 here is my EDA of UAE real estate
  Hedging with Real Estate/UAE Real Estate/Real Estate Data UAE/real-estate-data-uae-eda.ipynb
  Hedging with Real Estate/UAE Real Estate/Real Estate Data UAE/uae_properties.csv
Labels: GSSOC24, gssoc, level2

#690 here is my NY real Estate
  Hedging with Real Estate/NY Real Estate/.ipynb_checkpoints/ny-housing-eda-modeling-checkpoint.ipynb
  Hedging with Real Estate/NY Real Estate/NY-House-Dataset.csv
  Hedging with Real Estate/NY Real Estate/ny-housing-eda-modeling.ipynb
Labels: GSSOC24, gssoc, level2

#693 Landing Club Loan Analysis
  Loan Status Prediction/Lending Club Loan Analysis/Dataset/Dataset.md
  Loan Status Prediction/Lending Club Loan Analysis/Images/Accuracy of Model.PNG
  Loan Status Prediction/Lending Club Loan Analysis/Images/Area Plots/Area Plot 2.PNG
  Loan Status Prediction/Lending Club Loan Analysis/Images/Area Plots/Area Plot 3.PNG
  Loan Status Prediction/Lending Club Loan Analysis/Images/Area Plots/Area Plot 4.PNG
  Loan Status Prediction/Lending Club Loan Analysis/Images/Area Plots/Area Plots .PNG
  Loan Status Prediction/Lending Club Loan Analysis/Images/Confusion Matrix (1).PNG
  Loan Status Prediction/Lending Club Loan Analysis/Images/Important Plots/Plot 1.PNG
  Loan Status Prediction/Lending Club Loan Analysis/Images/Important Plots/Plot 2.PNG
  Loan Status Prediction/Lending Club Loan Analysis/Images/Important Plots/Plot 3.PNG
  Loan Status Prediction/Lending Club Loan Analysis/Images/Important Plots/Plot 4.PNG
  Loan Status Prediction/Lending Club Loan Analysis/Images/Important Plots/Plot 5.PNG
  Loan Status Prediction/Lending Club Loan Analysis/Images/Important Plots/Plot 6.PNG
  Loan Status Prediction/Lending Club Loan Analysis/Models/Lending_Club_Loan_Analysis.ipynb
  Loan Status Prediction/Lending Club Loan Analysis/Models/Lending_Club_Loan_Analysis_(Logistic_Regression_,_Decision_Tree_,_Random_Forest,ANN)_Model.ipynb
  Loan Status Prediction/Lending Club Loan Analysis/Models/Lending_Club_Loan_Analysis_KNN_Model.ipynb
  Loan Status Prediction/Lending Club Loan Analysis/Models/README.md
  Loan Status Prediction/Lending Club Loan Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#694 add foreign exchange rate prediction
  Exchange Traded Funds/Foreign Exchange Rate Prediction/Dataset/Foreign_Exchange_Rates.csv
  Exchange Traded Funds/Foreign Exchange Rate Prediction/Model/LSTM_model.ipynb
  Exchange Traded Funds/Foreign Exchange Rate Prediction/README.md
Labels: GSSOC24, gssoc, level2

#591 Here is my Qualcom stock prediction
  NYSE/Qualcomm Stocks/.ipynb_checkpoints/Qualcom stocks-checkpoint.ipynb
  NYSE/Qualcomm Stocks/Qualcom stocks.ipynb
  NYSE/Qualcomm Stocks/Qualcomm_Stocks.csv
Labels: GSSOC24, gssoc, level2

#597 here is my Reliance stock data
  Nifty /Reliance stock data/RELIANCE.csv
  Nifty /Reliance stock data/reliance stock data.ipynb
Labels: GSSOC24, gssoc, level2

#699 here is my Fraud detection by using logistic regression
  Company Bankruptcy Prediction/Fraud detection by using ML/.ipynb_checkpoints/fraud-detection-checkpoint.ipynb
  Company Bankruptcy Prediction/Fraud detection by using ML/fraud-detection.ipynb
Labels: GSSOC24, gssoc, level2

#702 here is my New delhi house prediction
  Hedging with Real Estate/New delhi house prediction/June_8_data_metro_closest_stations.csv
  Hedging with Real Estate/New delhi house prediction/New Delhi.ipynb
Labels: GSSOC24, gssoc, level2

#704 here is my London renting EDA
  Hedging with Real Estate/London renting house/.ipynb_checkpoints/london-checkpoint.ipynb
  Hedging with Real Estate/London renting house/london.ipynb
  Hedging with Real Estate/London renting house/rent_ads_rightmove_extended.csv
Labels: GSSOC24, gssoc, level2

#706 here is my Hydrabad house prediction
  Hedging with Real Estate/Hydrabad house prediction/.ipynb_checkpoints/Hydrabad by logistic-checkpoint.ipynb
  Hedging with Real Estate/Hydrabad house prediction/Hyderbad_House_price.csv
  Hedging with Real Estate/Hydrabad house prediction/Hydrabad by logistic.ipynb
Labels: GSSOC24, gssoc, level2

#707 here is my Philippines Housing Market
  Hedging with Real Estate/Philippines Housing Market/Housing_v2.csv
  Hedging with Real Estate/Philippines Housing Market/PH_Housing.csv
  Hedging with Real Estate/Philippines Housing Market/Philippines Housing Market.ipynb
Labels: GSSOC24, gssoc, level2

#709 here is my paris house prediction
  Hedging with Real Estate/Paris house prediction/.ipynb_checkpoints/Paris-checkpoint.ipynb
  Hedging with Real Estate/Paris house prediction/Paris.ipynb
  Hedging with Real Estate/Paris house prediction/ParisHousing.csv
Labels: GSSOC24, gssoc, level2

#711 here is my Boston
  Hedging with Real Estate/Boston house prediction/Boston.ipynb
  Hedging with Real Estate/Boston house prediction/boston.csv
Labels: GSSOC24, gssoc, level2

#662 Here is my Walmart EDA Prediction
  Hedging with Real Estate/.DS_Store
  NYSE/Walmart Stock Price Prediction/.DS_Store
  NYSE/Walmart Stock Price Prediction/Walmart stock EDA with prediction /walmart-sales-dataset-of-45stores.csv
  NYSE/Walmart Stock Price Prediction/Walmart stock EDA with prediction /walmart.ipynb
Labels: GSSOC24, gssoc, level2

#722 Cipla Stock Price Prediction Using LSTM, SVM, SVR, KNN and K Means Clustering
  Nifty /Cipla Stock Analysis/Dataset/CIPLA.csv
  Nifty /Cipla Stock Analysis/Images/Screenshot 2024-07-27 135540.png
  Nifty /Cipla Stock Analysis/Images/Screenshot 2024-07-27 135605.png
  Nifty /Cipla Stock Analysis/Images/Screenshot 2024-07-27 135616.png
  Nifty /Cipla Stock Analysis/Images/Screenshot 2024-07-27 135629.png
  Nifty /Cipla Stock Analysis/Images/Screenshot 2024-07-27 135639.png
  Nifty /Cipla Stock Analysis/Images/Screenshot 2024-07-27 135657.png
  Nifty /Cipla Stock Analysis/Images/Screenshot 2024-07-27 135725.png
  Nifty /Cipla Stock Analysis/Images/Screenshot 2024-07-27 135735.png
  Nifty /Cipla Stock Analysis/Model/Cipla_Stock_Price_Prediction_Using_LSTM,_SVM,_SVR,_KNN_and_K_Means_Clustering.ipynb
  Nifty /Cipla Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#737 Tail Risk Hedging added
  Finacial Domain/Tail Risk Hedging/Tail_Risk_Hedging_strategy.ipynb
  Finacial Domain/Tail Risk Hedging/readme.md
  Finacial Domain/Tail Risk Hedging/tail_risk_hedging_data.csv
Labels: GSSOC24, gssoc, level2

#739 Optimal Retirement Planning Using Deep Learning added
  Finacial Domain/Optimal Retirement Planning Using Deep Learning/eda_pairplot.png
  Finacial Domain/Optimal Retirement Planning Using Deep Learning/optimal_retirement_planning.ipynb
  Finacial Domain/Optimal Retirement Planning Using Deep Learning/readme.md
  Finacial Domain/Optimal Retirement Planning Using Deep Learning/retirement_planning_data.csv
Labels: GSSOC24, gssoc, level2

#740 Mortgage Default Prediction added
  Finacial Domain/Mortgage Default Prediction/Mortgage_Default_Prediction.ipynb
  Finacial Domain/Mortgage Default Prediction/mortgage_default_prediction.csv
  Finacial Domain/Mortgage Default Prediction/readme.md
Labels: GSSOC24, gssoc, level2

#742 Financial Market Crash Prediction added
  Finacial Domain/Financial Market Crash Prediction/Financial_Market_Crash_Prediction.ipynb
  Finacial Domain/Financial Market Crash Prediction/eda_correlation.png
  Finacial Domain/Financial Market Crash Prediction/eda_pairplot.png
  Finacial Domain/Financial Market Crash Prediction/financial_market_crash_data.csv
  Finacial Domain/Financial Market Crash Prediction/readme.md
Labels: GSSOC24, gssoc, level2

#743 Derivative Pricing Models Using Deep Learning added
  Finacial Domain/Derivative Pricing Models Using Deep Learning/Derivative_Pricing_Models_Using_Deep_Learning.ipynb
  Finacial Domain/Derivative Pricing Models Using Deep Learning/derivative_pricing_data.csv
  Finacial Domain/Derivative Pricing Models Using Deep Learning/readme.md
Labels: GSSOC24, gssoc, level2

#744 Dynamic Asset Allocation Using Deep Learning added
  Finacial Domain/Dynamic Asset Allocation Using Deep Learning/Dynamic_Asset_Allocation_Using_Deep_Learning.ipynb
  Finacial Domain/Dynamic Asset Allocation Using Deep Learning/dynamic_asset_allocation_data.csv
  Finacial Domain/Dynamic Asset Allocation Using Deep Learning/readme.md
Labels: GSSOC24, gssoc, level2

#745 Dynamic Rebalancing Strategy added
  Finacial Domain/Dynamic Rebalancing Strategy/dynamic_rebalancing_strategy.csv
  Finacial Domain/Dynamic Rebalancing Strategy/market_regime_detection.ipynb
  Finacial Domain/Dynamic Rebalancing Strategy/readme.md
Labels: GSSOC24, gssoc, level2

#747 Alternative Data for Investment added
  Finacial Domain/Alternative Data for Investment/Alternative_Data_for_Investment.ipynb
  Finacial Domain/Alternative Data for Investment/alternative_data_investment.csv
  Finacial Domain/Alternative Data for Investment/readme.md
Labels: GSSOC24, gssoc, level2

#748 Market Regime Detection added
  Finacial Domain/Market Regime Detection/market_regime_detection.csv
  Finacial Domain/Market Regime Detection/market_regime_detection.ipynb
  Finacial Domain/Market Regime Detection/readme.md
Labels: GSSOC24, gssoc, level2

#723 Added Bank Customer Churn Prediction
  Finacial Domain/Bank-Customer-Churn-Prediction/Bank.ipynb
  Finacial Domain/Bank-Customer-Churn-Prediction/README.md
  Finacial Domain/Bank-Customer-Churn-Prediction/churn.csv
  Finacial Domain/Bank-Customer-Churn-Prediction/images/Churn distribution based on Age.jpg
  Finacial Domain/Bank-Customer-Churn-Prediction/images/Churn distribution based on gender.jpg
  Finacial Domain/Bank-Customer-Churn-Prediction/images/Customer Churn Distribution.jpg
  Finacial Domain/Bank-Customer-Churn-Prediction/images/Distribution of Exited based on Location.jpg
  Finacial Domain/Bank-Customer-Churn-Prediction/images/classification report.jpg
  Finacial Domain/Bank-Customer-Churn-Prediction/images/confusion matrix.jpg
  Finacial Domain/Bank-Customer-Churn-Prediction/images/feature importance.jpg
  Finacial Domain/Bank-Customer-Churn-Prediction/images/models.jpg
Labels: GSSOC24, gssoc, level2

#753 added Health Insurance Price Prediction using Machine Learning (Issue #697)
  Finacial Domain/Health Insurance Price Prediction/Health_insurance_cost_prediction.ipynb
  Finacial Domain/Health Insurance Price Prediction/Images/boxplot-1.png
  Finacial Domain/Health Insurance Price Prediction/Images/boxplot-2_processed.png
  Finacial Domain/Health Insurance Price Prediction/Images/correlation_matrix.png
  Finacial Domain/Health Insurance Price Prediction/Images/countplot.png
  Finacial Domain/Health Insurance Price Prediction/Images/cross_validation_graph.png
  Finacial Domain/Health Insurance Price Prediction/Images/evaluation_metrix_comparison_all_models.png
  Finacial Domain/Health Insurance Price Prediction/Images/gbm_actual_vs_predicted.png
  Finacial Domain/Health Insurance Price Prediction/Images/histogram (1).png
  Finacial Domain/Health Insurance Price Prediction/Images/mlr_actual_vs_predicted.png
  Finacial Domain/Health Insurance Price Prediction/Images/pie-chart-1.png
  Finacial Domain/Health Insurance Price Prediction/Images/pie-chart-2.png
  Finacial Domain/Health Insurance Price Prediction/Images/rf_actual_vs_predicted.png
  Finacial Domain/Health Insurance Price Prediction/Images/scatterplot.png
  Finacial Domain/Health Insurance Price Prediction/Images/violin-plot.png
  Finacial Domain/Health Insurance Price Prediction/Images/xgboost_actual_Vs_predicted.png
  Finacial Domain/Health Insurance Price Prediction/app.py
  Finacial Domain/Health Insurance Price Prediction/readme.md
  Finacial Domain/Health Insurance Price Prediction/requirements.txt
Labels: GSSOC24, gssoc, level3

#632 Solved #572- Analyzing the Impact of Economic Indicators on Stock Prices
  Finacial Domain/Analyzing the Impact of Economic Indicators on Stock Prices/code.py
  Finacial Domain/Analyzing the Impact of Economic Indicators on Stock Prices/sd254_users.csv
Labels: GSSOC24, gssoc, level2

#717 #665 Added ASELSAN Stock Price Prediction
  NYSE/ASELSAN Stock Prices\/Dataset/ASELSAN-2017-2022.csv
  NYSE/ASELSAN Stock Prices\/Images/180611222-bcbf5e61-cc74-4ba7-9b90-89f2cfd2919f.png
  NYSE/ASELSAN Stock Prices\/Images/180611224-e1b325ff-605f-46dc-b5d5-c145a673c13c.png
  NYSE/ASELSAN Stock Prices\/Images/180611225-f63eae85-7e3c-421a-8f40-241884ed2bf1.png
  NYSE/ASELSAN Stock Prices\/Images/180611229-fefa8ec1-54bd-46fc-9e4b-746793dbf8fd.png
  NYSE/ASELSAN Stock Prices\/Images/180611233-6f68df38-beb3-48bd-8c13-80e61d60ea09.png
  NYSE/ASELSAN Stock Prices\/Images/180611235-a9ddbea7-2717-4032-bcfe-a2e8677ee461.png
  NYSE/ASELSAN Stock Prices\/Images/180611257-0ac8cc5c-6947-4dba-8547-0fc5342a281a.png
  NYSE/ASELSAN Stock Prices\/Images/180611261-e80e1bf5-7805-44d3-aa8e-83686bbc454d.png
  NYSE/ASELSAN Stock Prices\/Model/ASELSAN Stock Prices.ipynb
  NYSE/ASELSAN Stock Prices\/Model/README.md
Labels: GSSOC24, gssoc, level2

#718 #666 Added Doge INR Analysis
  Decentralized Finance/Doge INR Analysis/Dataset/DOGE-INR.csv
  Decentralized Finance/Doge INR Analysis/Dataset/dataset.md
  Decentralized Finance/Doge INR Analysis/Images/close price scatter.png
  Decentralized Finance/Doge INR Analysis/Images/high price.png
  Decentralized Finance/Doge INR Analysis/Images/high price_scatter.png
  Decentralized Finance/Doge INR Analysis/Images/linear.png
  Decentralized Finance/Doge INR Analysis/Images/low price.png
  Decentralized Finance/Doge INR Analysis/Images/open price.png
  Decentralized Finance/Doge INR Analysis/Images/open price_scatter.png
  Decentralized Finance/Doge INR Analysis/Images/ploy.png
  Decentralized Finance/Doge INR Analysis/Images/residual.png
  Decentralized Finance/Doge INR Analysis/Images/volume.png
  Decentralized Finance/Doge INR Analysis/Model/README.md
  Decentralized Finance/Doge INR Analysis/Model/dogecoin-inr-price-analysis.ipynb
  README.md
Labels: GSSOC24, gssoc, level2

#710 here is my pune house prediction
  Hedging with Real Estate/Nashik house prediction/Nashik.ipynb
  Hedging with Real Estate/Nashik house prediction/final_data.csv
Labels: GSSOC24, gssoc, level2

#806 Loan eligible prediction
  Loan Status Prediction/Loan eligible prediction/Loan_Eligibility_prediction.ipynb
  Loan Status Prediction/Loan eligible prediction/README.md
Labels: GSSOC24, gssoc, level2

#757 here is my USA stocks
  NYSE/USA stocks/.ipynb_checkpoints/lstm-stocks-prediction-checkpoint.ipynb
  NYSE/USA stocks/0050.csv
  NYSE/USA stocks/0050_1.png
  NYSE/USA stocks/0050_2.png
  NYSE/USA stocks/INTC.csv
  NYSE/USA stocks/Intel_1.png
  NYSE/USA stocks/Intel_2.png
  NYSE/USA stocks/SPY.csv
  NYSE/USA stocks/SPY_1.png
  NYSE/USA stocks/SPY_2.png
  NYSE/USA stocks/TSMC.csv
  NYSE/USA stocks/TSMC_1.png
  NYSE/USA stocks/TSMC_2.png
  NYSE/USA stocks/lstm-stocks-prediction.ipynb
Labels: GSSOC24, gssoc, level2

#663 Here is my S&P 500 Companies EDA
  NYSE/S&P 500 Companies EDA/.ipynb_checkpoints/s-p-500-checkpoint.ipynb
  NYSE/S&P 500 Companies EDA/s-p-500.ipynb
  NYSE/S&P 500 Companies EDA/sp500-companies.csv
  NYSE/S&P 500 Companies EDA/sp500-constituents.csv
Labels: GSSOC24, gssoc, level2

#811 Anomaly Detection in Transactions using Deep Learning added
  Finacial Domain/Anomaly Detection in Transactions using Deep Learning/Anomaly_Detection_in_Transactions_using_Deep_Learning.ipynb
  Finacial Domain/Anomaly Detection in Transactions using Deep Learning/readme.md
  Finacial Domain/Anomaly Detection in Transactions using Deep Learning/transactions.csv
Labels: GSSOC24, gssoc, level2

#626 here is my MRF stock prediction
  Nifty /MRF stock prediction/.ipynb_checkpoints/MRF stock prediction lstm-checkpoint.ipynb
  Nifty /MRF stock prediction/MRF stock prediction lstm.ipynb
  Nifty /MRF stock prediction/MRF.NS.csv
Labels: GSSOC24, gssoc, level2

#769 here is my china stocks
  China stocks/.ipynb_checkpoints/china stocks-checkpoint.ipynb
  China stocks/22_CSI100.csv
  China stocks/china stocks.ipynb
Labels: GSSOC24, gssoc, level2

#772 Add Mastercard Stock Analysis with LSTM and GRU
  NYSE/MasterCard Stock Price Analysis.ipynb
Labels: GSSOC24, gssoc, level2

#777 here is my house prediction model by using Stack Regression + Polyno…
  Hedging with Real Estate/House Prediction Stack Regression + Polynomial Regression/Main.ipynb
  Hedging with Real Estate/House Prediction Stack Regression + Polynomial Regression/Real estate.csv
Labels: GSSOC24, gssoc, level2

#779 here is my House prediction by using ANN model
  Hedging with Real Estate/House Prediction By using ANN/House prediction by ANN.ipynb
  Hedging with Real Estate/House Prediction By using ANN/Real estate.csv
Labels: GSSOC24, gssoc, level2

#785 here is my house prediction of Utah
  Hedging with Real Estate/Real Estate Data Utah/.ipynb_checkpoints/utah-analysis-and-prediction-checkpoint.ipynb
  Hedging with Real Estate/Real Estate Data Utah/real_estate_utah.csv
  Hedging with Real Estate/Real Estate Data Utah/utah-analysis-and-prediction.ipynb
Labels: GSSOC24, gssoc, level3

#788 here is my Credit card customer segmentation
  Credit Risk/Credit card customer segmentation/.ipynb_checkpoints/credit-card-customer-segmentation-checkpoint.ipynb
  Credit Risk/Credit card customer segmentation/BankChurners.csv
  Credit Risk/Credit card customer segmentation/credit-card-customer-segmentation.ipynb
Labels: GSSOC24, gssoc, level2

#790 here is my german credit card prediction
  Credit Risk/German credit card/.ipynb_checkpoints/credit-card-fraud-detection-checkpoint.ipynb
  Credit Risk/German credit card/GermanCredit.csv
  Credit Risk/German credit card/credit_card_model.pkl
  Credit Risk/German credit card/german.ipynb
Labels: GSSOC24, gssoc, level2

#802 Automated Financial Reporting with Deep Learning added
  Finacial Domain/Automated Financial Reporting with Deep Learning/app.py
  Finacial Domain/Automated Financial Reporting with Deep Learning/financial_data.csv
  Finacial Domain/Automated Financial Reporting with Deep Learning/financial_model.h5
  Finacial Domain/Automated Financial Reporting with Deep Learning/financial_report.csv
  Finacial Domain/Automated Financial Reporting with Deep Learning/financial_summary.csv
  Finacial Domain/Automated Financial Reporting with Deep Learning/readme.md
Labels: GSSOC24, gssoc, level3

#813 Dynamic Margin Requirements Prediction added
  Finacial Domain/Dynamic Margin Requirements Prediction/Dynamic_Margin_Requirements_Prediction.ipynb
  Finacial Domain/Dynamic Margin Requirements Prediction/dynamic_margin_requirements.csv
  Finacial Domain/Dynamic Margin Requirements Prediction/readme.md
Labels: GSSOC24, gssoc, level2

#804 Loan Default Prediction added
  Finacial Domain/Loan Default Prediction/LoanDefaultPrediction.ipynb
  Finacial Domain/Loan Default Prediction/app.py
  Finacial Domain/Loan Default Prediction/loan_default_data.csv
  Finacial Domain/Loan Default Prediction/readme.md
Labels: GSSOC24, gssoc, level3

#814 Hero MotoCorp Stock Price Prediction Using LSTM, SVM, SGD, KNN and K Means Clustering
  Nifty /Hero MotoCorp Stock Analysis/Dataset/HEROMOTOCO.csv
  Nifty /Hero MotoCorp Stock Analysis/Images/Screenshot 2024-07-30 215154.png
  Nifty /Hero MotoCorp Stock Analysis/Images/Screenshot 2024-07-30 215206.png
  Nifty /Hero MotoCorp Stock Analysis/Images/Screenshot 2024-07-30 215213.png
  Nifty /Hero MotoCorp Stock Analysis/Images/Screenshot 2024-07-30 215223.png
  Nifty /Hero MotoCorp Stock Analysis/Images/Screenshot 2024-07-30 215230.png
  Nifty /Hero MotoCorp Stock Analysis/Images/Screenshot 2024-07-30 215238.png
  Nifty /Hero MotoCorp Stock Analysis/Images/Screenshot 2024-07-30 215246.png
  Nifty /Hero MotoCorp Stock Analysis/Images/Screenshot 2024-07-30 215254.png
  Nifty /Hero MotoCorp Stock Analysis/Model/Hero_MotoCorp_Stock_Price_Prediction_Using_LSTM,_SVM,_SGD,_KNN_and_K_Means_Clustering.ipynb
  Nifty /Hero MotoCorp Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#815 Stock Market Bubble Detection added
  Finacial Domain/Stock Market Bubble Detection/Stock_Market_Bubble_Detection.ipynb
  Finacial Domain/Stock Market Bubble Detection/readme.md
  Finacial Domain/Stock Market Bubble Detection/stock_market_bubble.csv
Labels: GSSOC24, gssoc, level2

#816 Predicting Stock Splits and Dividends
  Finacial Domain/Predicting Stock Splits and Dividends/Predicting_Stock_Splits_and_Dividends.ipynb
  Finacial Domain/Predicting Stock Splits and Dividends/readme.md
  Finacial Domain/Predicting Stock Splits and Dividends/stock_splits_dividends.csv
Labels: GSSOC24, gssoc, level2

#817 Macroeconomic Scenario Analysis Enhancement added
  Finacial Domain/Macroeconomic Scenario Analysis Enhancement/Macroeconomic_Scenario_Analysis_Enhancement_using_Deep_Learning.ipynb
  Finacial Domain/Macroeconomic Scenario Analysis Enhancement/macroeconomic_data.csv
  Finacial Domain/Macroeconomic Scenario Analysis Enhancement/readme.md
Labels: GSSOC24, gssoc, level2

#818 Financial Crisis Early Warning System added
  Finacial Domain/Financial Crisis Early Warning System/Financial_Crisis_Early_Warning_System.ipynb
  Finacial Domain/Financial Crisis Early Warning System/financial_crisis_data.csv
  Finacial Domain/Financial Crisis Early Warning System/readme.md
Labels: GSSOC24, gssoc, level2

#823 Solved #820- Analyzing the Impact of User Demographics on Financial Metrics
  Finacial Domain/Analyzing the Impact of User Demographics on Financial Metrics/code.py
  Finacial Domain/Analyzing the Impact of User Demographics on Financial Metrics/sd254_users.csv
Labels: GSSOC24, gssoc, level2

#768 here is my Pune
  .DS_Store
  Hedging with Real Estate/Pune house rent prediction/house-rent-prediction-pune.ipynb
  Hedging with Real Estate/Pune house rent prediction/test.csv
Labels: GSSOC24, gssoc, level3

#835 here is my yes bank stocks
  Nifty /Yes Bank Stock Price Prediction/.ipynb_checkpoints/yes bank stock price prediction-checkpoint.ipynb
  Nifty /Yes Bank Stock Price Prediction/.ipynb_checkpoints/yes bank-checkpoint.ipynb
  Nifty /Yes Bank Stock Price Prediction/YesBank_StockPrices.csv
  Nifty /Yes Bank Stock Price Prediction/yes bank.ipynb
Labels: GSSOC24, gssoc, level2

#837 here is my model
  Finacial Domain/Swedish central bank interest rate and inflation/Interestrate and inflation Sweden 1908-2001.csv
  Finacial Domain/Swedish central bank interest rate and inflation/swedish economy 1908-2001.ipynb
Labels: GSSOC24, gssoc, level2

#838 Asset Correlation Analysis added
  Finacial Domain/Asset Correlation Analysis/Asset_Correlation_Analysis.ipynb
  Finacial Domain/Asset Correlation Analysis/app.py
  Finacial Domain/Asset Correlation Analysis/asset_prices.csv
  Finacial Domain/Asset Correlation Analysis/readme.md
Labels: GSSOC24, gssoc, level3

#839 Sustainable Finance Analytics added
  Finacial Domain/Sustainable Finance Analytics/Sustainable_Finance_Analytics.ipynb
  Finacial Domain/Sustainable Finance Analytics/esg_data.csv
  Finacial Domain/Sustainable Finance Analytics/readme.md
Labels: GSSOC24, gssoc, level2
