Repository Akshat111111/Hedging-of-Financial-Derivatives, pull requests merged in 2024-08, with the labels that each got.

#841 IPO performance added
  Finacial Domain/IPO performance/app.py
  Finacial Domain/IPO performance/dataset/ipo_data.csv
  Finacial Domain/IPO performance/models/IPO_performance.ipynb
  Finacial Domain/IPO performance/models/readme.md
Labels: GSSOC24, gssoc, level3

#843 Apple Stock Price Prediction Based on 40 Years
  NYSE/Apple Stock Analysis/Apple Stock Price Prediction Based on 40 Years/Dataset/Dataset.md
  NYSE/Apple Stock Analysis/Apple Stock Price Prediction Based on 40 Years/Images/Close Price History Plot.png
  NYSE/Apple Stock Analysis/Apple Stock Price Prediction Based on 40 Years/Images/Correlation Matrix (1).png
  NYSE/Apple Stock Analysis/Apple Stock Price Prediction Based on 40 Years/Images/Cross Price Seasonality.png
  NYSE/Apple Stock Analysis/Apple Stock Price Prediction Based on 40 Years/Images/Histogram.png
  NYSE/Apple Stock Analysis/Apple Stock Price Prediction Based on 40 Years/Images/Prophet Model.png
  NYSE/Apple Stock Analysis/Apple Stock Price Prediction Based on 40 Years/Images/Scatter Plot.png
  NYSE/Apple Stock Analysis/Apple Stock Price Prediction Based on 40 Years/Model/apple-stock-predictions-lstm-conv1d.ipynb
  NYSE/Apple Stock Analysis/Apple Stock Price Prediction Based on 40 Years/Model/apple-stock-predictions-lstm.ipynb
  NYSE/Apple Stock Analysis/Apple Stock Price Prediction Based on 40 Years/Model/apple-stock-predictions-using-prophet-model.ipynb
  NYSE/Apple Stock Analysis/Apple Stock Price Prediction Based on 40 Years/README.md
Labels: GSSOC24, gssoc, level2

#845 Added forex price prediction
  forex/Forex-Price-Prediction/README.md
  forex/Forex-Price-Prediction/data/GOOG.csv
  forex/Forex-Price-Prediction/data/IBM.csv
  forex/Forex-Price-Prediction/main.ipynb
  forex/Forex-Price-Prediction/plots/IBM_Close_Price.png
  forex/Forex-Price-Prediction/plots/IBM_Volume.png
  forex/Forex-Price-Prediction/plots/architecture.png
  forex/Forex-Price-Prediction/plots/data_separation.png
  forex/Forex-Price-Prediction/plots/final_model_metrics.png
  forex/Forex-Price-Prediction/plots/final_preds.png
  forex/Forex-Price-Prediction/plots/initial_model_metrics.png
  forex/Forex-Price-Prediction/plots/initial_preds.png
Labels: GSSOC24, gssoc, level2

#912 here is my Uber stock EDA App
  Financial APIs/Uber stock EDA App/ EDA app.py
  Financial APIs/Uber stock EDA App/Screenshot 2024-08-03 at 1.18.03 AM.png
  Financial APIs/Uber stock EDA App/UBER.csv
  Financial APIs/Uber stock EDA App/readme.md
Labels: GSSOC24, gssoc, level3

#876 here is my coca cola stock EDA app
  Financial APIs/Coca cola stock EDA app/Coca cola EDA stocks app.py
  Financial APIs/Coca cola stock EDA app/Coca-Cola_stock_history.csv
  Financial APIs/Coca cola stock EDA app/Screenshot 2024-08-03 at 1.18.03 AM.png
  Financial APIs/Coca cola stock EDA app/readme.md
Labels: GSSOC24, gssoc, level3

#860 china stock analysis using the Random Forest Regressor
  China stocks/china stocks.ipynb
  China stocks/china_stocks.ipynb
Labels: GSSOC24, gssoc, level1

#877 here is my app of big tech gaint stock EDA
  Financial APIs/Big Tech Giants Stock Price Data stock App/Screenshot 2024-08-03 at 1.18.03 AM.png
  Financial APIs/Big Tech Giants Stock Price Data stock App/Walmart EDA stocks app.py
  Financial APIs/Big Tech Giants Stock Price Data stock App/big_tech_companies.csv
  Financial APIs/Big Tech Giants Stock Price Data stock App/readme.md
Labels: GSSOC24, gssoc, level3

#868 here is my indian startup analysis
  Finacial Domain/Indian Startup Funding analysis/Indian startup.ipynb
  Finacial Domain/Indian Startup Funding analysis/startup_funding.csv
Labels: GSSOC24, gssoc, level2

#861 Corporate Credit Rating Forecasting
  Finacial Domain/Predicting Corporate Earnings Using Deep Learning/Corporate Credit Rating Forecasting/Dataset/corporate_rating.csv
  Finacial Domain/Predicting Corporate Earnings Using Deep Learning/Corporate Credit Rating Forecasting/Dataset/us_stocks.csv
  Finacial Domain/Predicting Corporate Earnings Using Deep Learning/Corporate Credit Rating Forecasting/README.md
  Finacial Domain/Predicting Corporate Earnings Using Deep Learning/Corporate Credit Rating Forecasting/corporateCreditRatingPrediction.ipynb
  Finacial Domain/Predicting Corporate Earnings Using Deep Learning/Corporate Credit Rating Forecasting/generateCreditRatingDataset.py
  Finacial Domain/Predicting Corporate Earnings Using Deep Learning/Corporate Credit Rating Forecasting/output.html
Labels: GSSOC24, gssoc, level2

#863 here is my Mac donald stocks
  NYSE/Mc Donald's Stock Price/UPDOWND.xlsx
  NYSE/Mc Donald's Stock Price/decision-tree-and-random-forest.ipynb
Labels: GSSOC24, gssoc, level2

#869 here is my AMD stock visuvalization
  Financial APIs/AMD Stock prediction Visuvalization/.idea/.gitignore
  Financial APIs/AMD Stock prediction Visuvalization/.idea/Visuvalization.iml
  Financial APIs/AMD Stock prediction Visuvalization/.idea/inspectionProfiles/Project_Default.xml
  Financial APIs/AMD Stock prediction Visuvalization/.idea/inspectionProfiles/profiles_settings.xml
  Financial APIs/AMD Stock prediction Visuvalization/.idea/misc.xml
  Financial APIs/AMD Stock prediction Visuvalization/.idea/modules.xml
  Financial APIs/AMD Stock prediction Visuvalization/AMD.csv
  Financial APIs/AMD Stock prediction Visuvalization/AMD_model.h5
  Financial APIs/AMD Stock prediction Visuvalization/Screenshot 2024-08-03 at 12.12.48 AM.png
  Financial APIs/AMD Stock prediction Visuvalization/prediction_plots.png
  Financial APIs/AMD Stock prediction Visuvalization/readme.md
  Financial APIs/AMD Stock prediction Visuvalization/stocks app.py
Labels: GSSOC24, gssoc, level3

#870 here is my Qualcomm stocks visuvalization
  Financial APIs/Qualcomm EDA Visuvalization App/.idea/.gitignore
  Financial APIs/Qualcomm EDA Visuvalization App/.idea/Visuvalization.iml
  Financial APIs/Qualcomm EDA Visuvalization App/.idea/inspectionProfiles/Project_Default.xml
  Financial APIs/Qualcomm EDA Visuvalization App/.idea/inspectionProfiles/profiles_settings.xml
  Financial APIs/Qualcomm EDA Visuvalization App/.idea/misc.xml
  Financial APIs/Qualcomm EDA Visuvalization App/.idea/modules.xml
  Financial APIs/Qualcomm EDA Visuvalization App/Qualcomm_Stocks.csv
  Financial APIs/Qualcomm EDA Visuvalization App/Screenshot 2024-08-03 at 1.18.03 AM.png
  Financial APIs/Qualcomm EDA Visuvalization App/eda_plots/readme.md
  Financial APIs/Qualcomm EDA Visuvalization App/stocks app.py
Labels: GSSOC24, gssoc, level2

#914 Solved #867- Time series analysis on spending patterns
  Time Series Analysis Models/time_series_analysis.py
Labels: GSSOC24, gssoc, level2

#844 Nestle India Stock Price Prediction Using LSTM, Linear Regression, KNN and K Means Clustering
  Nifty /Nestle India Stock Analysis/Dataset/NESTLEIND.csv
  Nifty /Nestle India Stock Analysis/Images/Screenshot 2024-07-31 225244.png
  Nifty /Nestle India Stock Analysis/Images/Screenshot 2024-07-31 225300.png
  Nifty /Nestle India Stock Analysis/Images/Screenshot 2024-07-31 225307.png
  Nifty /Nestle India Stock Analysis/Images/Screenshot 2024-07-31 225316.png
  Nifty /Nestle India Stock Analysis/Images/Screenshot 2024-07-31 225322.png
  Nifty /Nestle India Stock Analysis/Images/Screenshot 2024-07-31 225335.png
  Nifty /Nestle India Stock Analysis/Images/Screenshot 2024-07-31 225343.png
  Nifty /Nestle India Stock Analysis/Model/Nestle_India_Stock_Price_Prediction_Using_LSTM,_Linear_Regression,_KNN_and_K_Means_Clustering.ipynb
  Nifty /Nestle India Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#981 Startup Profit Prediction
  Finacial Domain/Indian Startup Funding analysis/Startup Profit Prediction/50_Startups.csv
  Finacial Domain/Indian Startup Funding analysis/Startup Profit Prediction/README.md
  Finacial Domain/Indian Startup Funding analysis/Startup Profit Prediction/Startup_Profit_Prediction.ipynb
Labels: GSSOC24, gssoc, level2

#990 Tesla stock
  NYSE/Tesla stock prediction by using LSTM/Tesla Historic Stock Price Analysis/Dataset/Dataset.md
  NYSE/Tesla stock prediction by using LSTM/Tesla Historic Stock Price Analysis/Images/CandlestickPlot.png
  NYSE/Tesla stock prediction by using LSTM/Tesla Historic Stock Price Analysis/Images/FanChart.png
  NYSE/Tesla stock prediction by using LSTM/Tesla Historic Stock Price Analysis/Images/LinePlot_ClosingPrice.png
  NYSE/Tesla stock prediction by using LSTM/Tesla Historic Stock Price Analysis/Images/LinePlot_Open.png
  NYSE/Tesla stock prediction by using LSTM/Tesla Historic Stock Price Analysis/Images/MovingAverage.png
  NYSE/Tesla stock prediction by using LSTM/Tesla Historic Stock Price Analysis/Models/tesla-ticker-bigru.ipynb
  NYSE/Tesla stock prediction by using LSTM/Tesla Historic Stock Price Analysis/Models/tesla-ticker-data-exploration-1.ipynb
  NYSE/Tesla stock prediction by using LSTM/Tesla Historic Stock Price Analysis/Models/tesla-ticker-data-exploration-2.ipynb
  NYSE/Tesla stock prediction by using LSTM/Tesla Historic Stock Price Analysis/Models/tesla-ticker-gru.ipynb
  NYSE/Tesla stock prediction by using LSTM/Tesla Historic Stock Price Analysis/README.md
Labels: GSSOC24, gssoc, level2

#883 here is my Itc EDA app
  Financial APIs/ITC stock EDA app/ITC EDA stocks app.py
  Financial APIs/ITC stock EDA app/ITC-EQ-01-04-2000-to-31-03-2024.csv
  Financial APIs/ITC stock EDA app/Screenshot 2024-08-03 at 1.18.03 AM.png
  Financial APIs/ITC stock EDA app/readme.md
Labels: GSSOC24, gssoc, level3

#952 here is my ICICI BANK EDA APP
  Financial APIs/ICICI BANK EDA APP/EDA app.py
  Financial APIs/ICICI BANK EDA APP/ICICIBANK.NS_data.csv
  Financial APIs/ICICI BANK EDA APP/Screenshot 2024-08-03 at 1.18.03 AM.png
  Financial APIs/ICICI BANK EDA APP/readme.md
Labels: GSSOC24, gssoc, level2

#1003 Added Regime Detection
  Finacial Domain/RegimeDetection/README.md
  Finacial Domain/RegimeDetection/RegimeDetection_Financial_Markets_KMeans.ipynb
Labels: GSSOC24, gssoc, level2

#1005 Added etf prediction in decentralized finance
  Decentralized Finance/ETH_price_Prediction/ETF_price_Prediction-main/README.md
  Decentralized Finance/ETH_price_Prediction/ETF_price_Prediction-main/ethLsmt.ipynb
Labels: GSSOC24, gssoc, level2

#929 Added Employee Turnover Prediction
  Finacial Domain/Employee_Turnover_Prediction/Dataset/HR.csv
  Finacial Domain/Employee_Turnover_Prediction/Model/Employee_Turnover_Prediction.ipynb
  Finacial Domain/Employee_Turnover_Prediction/requirements.txt
Labels: GSSOC24, gssoc, level2

#909 here is my MRF stock EDA app
  Financial APIs/MRF stock EDA  app/ EDA app.py
  Financial APIs/MRF stock EDA  app/MRF.NS.csv
  Financial APIs/MRF stock EDA  app/Screenshot 2024-08-03 at 1.18.03 AM.png
  Financial APIs/MRF stock EDA  app/readme.md
Labels: GSSOC24, gssoc, level2
