Repository Akshat111111/Hedging-of-Financial-Derivatives, pull requests merged in 2024-05, with the labels that each got.

#40 Made some spelling and indentation corrections and added more info to the documentation.
  Monte_Carlo_Simulation_GBM.ipynb
Labels: GSSOC24

#145 Gold price prediction
  Hedging with Gold/Gold_Price_Pred-MachineLearning/Dataset/FINAL_USO.csv
  Hedging with Gold/Gold_Price_Pred-MachineLearning/Images/output.png
  Hedging with Gold/Gold_Price_Pred-MachineLearning/README.md
  Hedging with Gold/Gold_Price_Pred-MachineLearning/model.ipynb
  Hedging with Gold/Gold_Price_Pred-MachineLearning/requirements.txt
Labels: GSSOC24, gssoc, level2

#147 added more contributions.
  README.md
Labels: GSSOC24, gssoc, level1

#154 Added workflow for closing old PRs
  .github/workflows/close-old-pr.yml
Labels: GSSOC24, gssoc, level2

#162 added workflow for autocomment on closing an issue
  .github/workflows/autocomment-iss-close.yml
Labels: GSSOC24, gssoc, level2

#165 Docs: added issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: GSSOC24, gssoc, level2

#167 Added more Mathematical models
  Credit Risk/CreditRisk.ipynb
Labels: GSSOC24, gssoc, level2

#170 Added foreign exchange rate prediction model
  forex/forex.ipynb
  forex/forex.py
Labels: GSSOC24, gssoc, level2

#180 Added the feature to auto comment on pr merged
  .github/workflows/auto-comment-on-pr-merge.yml
Labels: GSSOC24, gssoc, level2

#181 Added LSTM and ARIMA
  Facebook Prophet/FbProphet Nifty.ipynb
Labels: GSSOC24, gssoc, level2

#187 Ocr
  optical character recognition for financial docs/Readme.md
  optical character recognition for financial docs/image.jpg
  optical character recognition for financial docs/ocr_code.ipynb
Labels: GSSOC24, gssoc, level2

#190 [FEATURE]: Stock Price prediction using FB Prophet #185
  Stock_Price_Prediction_using_FB_Prophet/Close and yhat.png
  Stock_Price_Prediction_using_FB_Prophet/Forecast Evaluation using google sheets.txt
  Stock_Price_Prediction_using_FB_Prophet/README.md
  Stock_Price_Prediction_using_FB_Prophet/TSLA.csv
  Stock_Price_Prediction_using_FB_Prophet/Tesla_(TSLA)_Stock_Price_prediction_using_Facebook_Prophet.ipynb
  Stock_Price_Prediction_using_FB_Prophet/forecast.csv
  Stock_Price_Prediction_using_FB_Prophet/yhat.png
Labels: GSSOC24, gssoc, level2

#182 Updated dr1.py
  hedged-market-reinforcement-learning/Updated dr1.py
Labels: GSSOC24, gssoc, level3

#194 Enhanced credit risks model
  Credit Risk/CreditRisk.ipynb
Labels: GSSOC24, gssoc, level2

#199 Issue in autocommenting merged pr: #197
  .github/workflows/auto-comment-on-pr-merge.yml
Labels: GSSOC24, gssoc, level2

#201 Fixed Real Estate Price Prediction Model #48
  Hedging with Real Estate/New_Upgrade_Bengaluru_House_Price_Predition/bengaluru_house_prices.csv
  Hedging with Real Estate/New_Upgrade_Bengaluru_House_Price_Predition/bhp.csv
  Hedging with Real Estate/New_Upgrade_Bengaluru_House_Price_Predition/columns.json
  Hedging with Real Estate/New_Upgrade_Bengaluru_House_Price_Predition/df.pkl
  Hedging with Real Estate/New_Upgrade_Bengaluru_House_Price_Predition/house-price-prediction.ipynb
  Hedging with Real Estate/New_Upgrade_Bengaluru_House_Price_Predition/xgboostmodel.pkl
Labels: GSSOC24, gssoc, level2

#202 Added Advanced Visualizations to forex model
  forex/forex.ipynb
Labels: GSSOC24, gssoc, level3

#206 Decentralized finance
  Decentralized Finance/Readme.md
  Decentralized Finance/crypto.ipynb
  Indian Elections/.DS_Store
Labels: GSSOC24, gssoc, level2

#208 here is my model by using LSTM method with 99% accuracy
  .DS_Store
  exchange-rate-forecasting/.DS_Store
  exchange-rate-forecasting/Foreign Exchange Rate Prediction using LSTM/.ipynb_checkpoints/LSTM model-checkpoint.ipynb
  exchange-rate-forecasting/Foreign Exchange Rate Prediction using LSTM/Foreign_Exchange_Rates.csv
  exchange-rate-forecasting/Foreign Exchange Rate Prediction using LSTM/LSTM model.ipynb
Labels: GSSOC24, gssoc, level2

#211 Added Interactive visualisation to Indian elections model
  Indian Elections/generalelections.ipynb
Labels: GSSOC24, gssoc, level2

#212 Created additional visualizations for Indian Elections Model.
  Indian Elections/generalelections.ipynb
Labels: GSSOC24, gssoc, level2
