Repository Akshat111111/Hedging-of-Financial-Derivatives, pull requests merged in 2024-06, with the labels that each got.

#222 Added visualisations to loan status prediction Model
  Loan Status Prediction/Loan_Status_prediction.ipynb
Labels: GSSOC24, gssoc, level2

#229 Loan Status Prediction using Neural Networks
  Loan Status Prediction/loanprediction.ipynb
  README.md
Labels: GSSOC24, gssoc, level3

#231 Updated the PULL REQUEST readme template URGENT:🚨
  .github/pull_request_template.md
Labels: GSSOC24, gssoc, level1

#233 Loan Status Prediction (Model Enhancement , Visualizations , Hyperparameter Tuning)
  Loan Status Prediction/Loan_status_Machine_learning.ipynb
  Loan Status Prediction/README.md
Labels: GSSOC24, gssoc, level3

#236 House price web app
  HousePriceWebApp/.gitignore
  HousePriceWebApp/PIPELINE.pkl
  HousePriceWebApp/app.gif
  HousePriceWebApp/app.py
  HousePriceWebApp/dataframe.pkl
  HousePriceWebApp/readme.md
  HousePriceWebApp/requirements.txt
  HousePriceWebApp/utils.py
Labels: GSSOC24, gssoc, level3

#241 Netflix movies trend Analysis issue #179
  NYSE/netflix analysis/New Netflix Trend Analysis/Netflix_dataset.csv
  NYSE/netflix analysis/New Netflix Trend Analysis/netflix_trend.ipynb
Labels: GSSOC24, gssoc, level2

#245 Beta weighted stock portfolio implemented
  Beta-weighted-stock-portfolio/Readme.md
  Beta-weighted-stock-portfolio/betaweighted.ipynb
Labels: GSSOC24, gssoc, level2

#248 Added GBM Simulation
  Geometric_brownian_motion_simulation.ipynb
Labels: GSSOC24, gssoc, level2

#250 Credit Risk Prediction using Neural Networks
  Credit Risk/credit_risk_prediction.ipynb
Labels: GSSOC24, gssoc, level2

#256 Multiple Model Exploration on loan status prediction
  Loan Status Prediction/Loan_Status_prediction.ipynb
Labels: GSSOC24, gssoc, level2

#267 Model Enhancement using ensembling Models such as GradientBoosting , Adaboost and Stacking method
  Hedging with Real Estate/New_Upgrade_Bengaluru_House_Price_Predition/GradientBoostingRegressor.pkl
  Hedging with Real Estate/New_Upgrade_Bengaluru_House_Price_Predition/MoreModels.ipynb
  Hedging with Real Estate/New_Upgrade_Bengaluru_House_Price_Predition/StackingModel.png
Labels: GSSOC24, gssoc, level2

#273 Neural Network enhancement for Real Estate Project
  Hedging with Real Estate/New_Upgrade_Bengaluru_House_Price_Predition/NeuralNetworks.ipynb
Labels: GSSOC24, gssoc, level2

#274 Nifty Close Price Prediction using Neural Networks
  Nifty /Nifty Close Price Prediction using Neural Networks/Nifty.csv
  Nifty /Nifty Close Price Prediction using Neural Networks/Nifty_closeprice_prediction.ipynb
  Nifty /Nifty Close Price Prediction using Neural Networks/Readme.md
Labels: GSSOC24, gssoc, level2

#279 Loan status webapp
  Webapp/.gitignore
  Webapp/app.py
  Webapp/model.pkl
  Webapp/readme.md
  Webapp/sample.mp4
  Webapp/utils.py
Labels: GSSOC24, gssoc, level3

#277 Indian Currency Notes Classifier
  Indian Currency Detection using DL/Dataset/README.md
  Indian Currency Detection using DL/Images/DenseNet121/09ec2435-528f-467a-886c-5a6c563778c0.png
  Indian Currency Detection using DL/Images/DenseNet121/1aeba4fe-e49c-4f98-a78c-863e9105a6a8.png
  Indian Currency Detection using DL/Images/DenseNet121/43981767-5776-4649-bc6e-bee34ffac39c.png
  Indian Currency Detection using DL/Images/InceptionV3_predictions/32abcdf1-3a32-4a63-97ae-2500dee9bbb3.png
  Indian Currency Detection using DL/Images/InceptionV3_predictions/72d2062d-41f0-4455-9607-f437b4362a51.png
  Indian Currency Detection using DL/Images/InceptionV3_predictions/988c3a1f-cd99-4d61-b395-0b2617891bea.png
  Indian Currency Detection using DL/Images/NASNetMobile_predictions/28cea739-a49a-452d-8796-6d3069780991.png
  Indian Currency Detection using DL/Images/NASNetMobile_predictions/2e4cba78-0b17-4c85-9ee0-7bdd3522b9d1.png
  Indian Currency Detection using DL/Images/NASNetMobile_predictions/df1812d9-3e50-4de0-9024-af9d2f54d16e.png
  Indian Currency Detection using DL/Images/Resnet50V2_predictions/7cf8ba06-bb9e-4f23-9e39-c59923f3f300.png
  Indian Currency Detection using DL/Images/Resnet50V2_predictions/994bb09c-443a-4f94-a2b2-8457e0875228.png
  Indian Currency Detection using DL/Images/Resnet50V2_predictions/ce0ab66b-583d-4966-8848-bbe2032d5060.png
  Indian Currency Detection using DL/Images/Xception_predictions/1ee80672-8bf2-4946-a8c4-0c742949ae70.png
  Indian Currency Detection using DL/Images/Xception_predictions/5ddb2db6-6493-472e-9fb2-3510b6e214a2.png
  Indian Currency Detection using DL/Images/Xception_predictions/85aaddd6-dd79-42ad-b209-33f89cc5ff18.png
  Indian Currency Detection using DL/Images/bar.png
  Indian Currency Detection using DL/Images/image_path.png
  Indian Currency Detection using DL/Images/pie.png
  Indian Currency Detection using DL/Models/README.md
  Indian Currency Detection using DL/Models/models_IndianCurrencyDetection.ipynb
  Indian Currency Detection using DL/requirement.txt
Labels: GSSOC24, gssoc, level3

#293 Did Model Evaluation and Hyperparameter Tuning on Loan Status Prediction Model
  Loan Status Prediction/Loan_Status_prediction.ipynb
Labels: GSSOC24, gssoc, level2

#296 Enhanced Feature Engineering for Crisis Prediction
  finacial crisis of africa by using tensorflow/African_Crisis_Prediction.ipynb
  finacial crisis of africa by using tensorflow/Untitled.ipynb
Labels: GSSOC24, gssoc, level1

#304 Implemented two ensemble methods: a Voting Classifier and a Stacking Classifier on Loan Status Prediction Model.
  Loan Status Prediction/Loan_Status_prediction.ipynb
Labels: GSSOC24, gssoc, level1

#312 here is my segmentation model
  Hedging Currencies/Bank Customer Segmentation/.ipynb_checkpoints/bank-customer-segmentation-kmeans-hac-dbscan-checkpoint.ipynb
  Hedging Currencies/Bank Customer Segmentation/Bank_Personal_Loan_Modelling.xlsx
  Hedging Currencies/Bank Customer Segmentation/bank-customer-segmentation-kmeans-hac-dbscan.ipynb
  Hedging Currencies/Bank Customer Segmentation/pairplot1.png
Labels: GSSOC24, gssoc, level2

#308 Election Prediction App
  Indian Elections/Election_prediction-WebApp/LS_2.0.csv
  Indian Elections/Election_prediction-WebApp/Readme.md
  Indian Elections/Election_prediction-WebApp/app.py
  Indian Elections/Election_prediction-WebApp/images.jpeg
  python_web_app/AAPL.csv
  python_web_app/app.py
Labels: GSSOC24, gssoc, level3

#313 Enhanced Tesla (TSLA) Stock Price prediction using Facebook Prophet
  Stock_Price_Prediction_using_FB_Prophet/Tesla_(TSLA)_Stock_Price_prediction_using_Facebook_Prophet.ipynb
Labels: GSSOC24, gssoc, level1

#315 Enhanced Nifty Arima model.
  Nifty /Arima/modell.ipynb
Labels: GSSOC24, gssoc, level1

#316 LIME (Local Interpretable Model-agnostic Explanations) to explain Logistic Regression model of Loan Status Prediction model.
  Loan Status Prediction/Loan_Status_prediction.ipynb
Labels: GSSOC24, gssoc, level1

#323 Add Enhanced Model
  Credit Risk/Enhanced Credit Risk Prediction Model/Credit_risk.csv
  Credit Risk/Enhanced Credit Risk Prediction Model/Naive Model performance.png
  Credit Risk/Enhanced Credit Risk Prediction Model/credit_risk_prediction.ipynb
Labels: GSSOC24, gssoc, level3

#336 Credit Card Fraud Detection using Neural Networks
  Credit Card Fraud Detection/Readme.md
  Credit Card Fraud Detection/creditcard_fraud_detection.ipynb
Labels: GSSOC24, gssoc, level2

#343 Walmart stock Price Prediction Using LSTM, SGD And Random Forest
  NYSE/Walmart Stock Price Prediction/Dataset/README.md
  NYSE/Walmart Stock Price Prediction/Dataset/WMT.csv
  NYSE/Walmart Stock Price Prediction/Images/Disrtibution Of Walmart Daily Returns.png
  NYSE/Walmart Stock Price Prediction/Images/High Stock Prices.png
  NYSE/Walmart Stock Price Prediction/Images/Open Price vs Close Price.png
  NYSE/Walmart Stock Price Prediction/Images/Plotting Performance Using LSTM.png
  NYSE/Walmart Stock Price Prediction/Images/Stock Price.png
  NYSE/Walmart Stock Price Prediction/Model/README.md
  NYSE/Walmart Stock Price Prediction/Model/Walmart_stock_Price_Prediction_Using_LSTM,_SGD_And_Random_Forest.ipynb
  NYSE/Walmart Stock Price Prediction/requirements.txt
Labels: GSSOC24, gssoc, level2

#341 Add Telecom Churn Prediction and Airtel Stock Analysis
  telcochurn/AirtelStockPrediction/BHARTIARTL.NS.csv
  telcochurn/AirtelStockPrediction/airtel-stock-price-analysis-time-series-analysis.ipynb
  telcochurn/Readme.md
  telcochurn/WA_Fn-UseC_-Telco-Customer-Churn.csv
  telcochurn/telecom-churn-prediction.ipynb
Labels: GSSOC24, gssoc, level2

#352 Here is my Lottery Analysis
  .DS_Store
  Finacial Domain/lottery-uk analysis/.ipynb_checkpoints/lottery-uk-euromillions-all-data-eda-checkpoint.ipynb
  Finacial Domain/lottery-uk analysis/eum_df.csv
  Finacial Domain/lottery-uk analysis/lottery-uk-euromillions-all-data-eda.ipynb
Labels: GSSOC24, gssoc, level2

#362 Bitcoin Close Price Predictor using Neural Networks
  Decentralized Finance/Bitcoin Close Price Predictor/Readme.md
  Decentralized Finance/Bitcoin Close Price Predictor/bitcoin.csv
  Decentralized Finance/Bitcoin Close Price Predictor/bitcoin_close_price_prediction.ipynb
Labels: GSSOC24, gssoc, level2

#354 Bank Segmentation
  .gitattributes
  Company Bankruptcy Prediction/.gitattributes
  Company Bankruptcy Prediction/Bank Customer Segmentation.ipynb
  Company Bankruptcy Prediction/README.md
  README.md
Labels: GSSOC24, gssoc, level2

#351 Enhance Cointegration Strategy with Johansen Test
  Nifty/PairsTrading_johansen_cointegration_test.ipynb
Labels: GSSOC24, gssoc, level2

#360 here is my Axis bank prediction
  Nifty /.DS_Store
  Nifty /AXIS bank/.DS_Store
  Nifty /AXIS bank/AXIS BANK STOCK PRICE PREDICITION/.ipynb_checkpoints/axis bank stock price predicition-checkpoint.ipynb
  Nifty /AXIS bank/AXIS BANK STOCK PRICE PREDICITION/AXISBANK.csv
  Nifty /AXIS bank/AXIS BANK STOCK PRICE PREDICITION/axis bank stock price predicition.ipynb
Labels: GSSOC24, gssoc, level2

#375 Enhanced and Refactored "portfolio_optimisation.py".
  Quant-Finance-Library/iquant/portfolio_optimisation.py
Labels: GSSOC24, gssoc, level2

#372 Nvidia Stock Prediction
  NYSE/nvidia stock prediction/Readme.md
  NYSE/nvidia stock prediction/nvda_stock_data.csv
  NYSE/nvidia stock prediction/nvidia_stock_prediction.py
Labels: GSSOC24, gssoc, level2

#391 Sentiment Analysis on web scrapped data with groq API
  market-hedging-sentiment-analysis/Sentiment_Analysis (3).ipynb
Labels: GSSOC24, gssoc, level2

#399 Create realtime_risk_management.py
  Finacial Domain/realtime_risk_management.py
Labels: GSSOC24, gssoc, level1

#389 added Tesla Historic Stock Price Analysis
  NYSE/Tesla Historic Stock Price Analysis/Dataset/README.md
  NYSE/Tesla Historic Stock Price Analysis/Images/3D_SurfacePlot.png
  NYSE/Tesla Historic Stock Price Analysis/Images/CandlestickPlot.png
  NYSE/Tesla Historic Stock Price Analysis/Images/FanChart.png
  NYSE/Tesla Historic Stock Price Analysis/Images/LinePlot_ClosingPrice.png
  NYSE/Tesla Historic Stock Price Analysis/Images/LinePlot_Open.png
  NYSE/Tesla Historic Stock Price Analysis/Images/MovingAverage.png
  NYSE/Tesla Historic Stock Price Analysis/Model/tesla-ticker-bigru.ipynb
  NYSE/Tesla Historic Stock Price Analysis/Model/tesla-ticker-data-exploration-1.ipynb
  NYSE/Tesla Historic Stock Price Analysis/Model/tesla-ticker-data-exploration-2.ipynb
  NYSE/Tesla Historic Stock Price Analysis/Model/tesla-ticker-gru.ipynb
  NYSE/Tesla Historic Stock Price Analysis/README.md
Labels: GSSOC24, gssoc, level3

#404 Google advanced analysis
  NYSE/Google advanced analysis/StockMarket(NeuralNetwork).ipynb
  NYSE/Google advanced analysis/StockMarket.csv
  NYSE/Google advanced analysis/best_model_mlp.h5
  NYSE/Google advanced analysis/requirement.txt
Labels: GSSOC24, gssoc, level2

#397 Car Ownership prediction using Machine learning
  Finacial Domain/Car_Ownership_Prediction/Carcompany_Tesla_stock_price_prediction.ipynb
  Finacial Domain/Car_Ownership_Prediction/TSLA_historical_data.csv
  Finacial Domain/Car_Ownership_Prediction/app.py
  Finacial Domain/Car_Ownership_Prediction/car_ownership.csv
  Finacial Domain/Car_Ownership_Prediction/car_ownership_Data_Preprocessing.ipynb
  Finacial Domain/Car_Ownership_Prediction/car_ownership_prediction_model_training.ipynb
  Finacial Domain/Car_Ownership_Prediction/gradient_boosting_model.pkl
  Finacial Domain/Car_Ownership_Prediction/images/bar plot.png
  Finacial Domain/Car_Ownership_Prediction/images/box_plot.png
  Finacial Domain/Car_Ownership_Prediction/images/box_plot_credit_score.png
  Finacial Domain/Car_Ownership_Prediction/images/confusion matrix- random forest.png
  Finacial Domain/Car_Ownership_Prediction/images/confusion matrix-decision trees.png
  Finacial Domain/Car_Ownership_Prediction/images/confusion matrix-logistic regression.png
  Finacial Domain/Car_Ownership_Prediction/images/confusionm matrix- gradient boosting.png
  Finacial Domain/Car_Ownership_Prediction/images/count plot.png
  Finacial Domain/Car_Ownership_Prediction/images/model_comparison.png
  Finacial Domain/Car_Ownership_Prediction/images/pie chart-1.png
  Finacial Domain/Car_Ownership_Prediction/images/pie chart-2.png
  Finacial Domain/Car_Ownership_Prediction/images/violin-plot.png
  Finacial Domain/Car_Ownership_Prediction/processed_data_car.csv
  Finacial Domain/Car_Ownership_Prediction/readme.md
  Finacial Domain/Car_Ownership_Prediction/requirements.txt
  Finacial Domain/Car_Ownership_Prediction/webapp.mp4
Labels: GSSOC24, gssoc, level3

#408 Coca Cola Stock Price Prediction using LSTM, SVR, SGD, Decision Tree Regressor And Random Forest
  NYSE/Coca Cola Stock Analysis/Dataset/COCO COLA.csv
  NYSE/Coca Cola Stock Analysis/Images/Decision Tree Model Predictions vs True Values.png
  NYSE/Coca Cola Stock Analysis/Images/LSTM Model Predictions vs True Values.png
  NYSE/Coca Cola Stock Analysis/Images/Random Forest Model Predictions vs True Values.png
  NYSE/Coca Cola Stock Analysis/Images/SGD Model Predictions vs True Values.png
  NYSE/Coca Cola Stock Analysis/Images/SVR Model Predictions vs True Values.png
  NYSE/Coca Cola Stock Analysis/Images/Stock Close Price History.png
  NYSE/Coca Cola Stock Analysis/Model/Coca_Cola_Stock_Analysis.ipynb
  NYSE/Coca Cola Stock Analysis/requirements.txt
Labels: GSSOC24, gssoc, level2

#403 Stock market Data Scrapper from yahoo Finance
  Finacial Domain/Stock Market Data Scrapper/app.py
  Finacial Domain/Stock Market Data Scrapper/readme.md
  Finacial Domain/Stock Market Data Scrapper/requirements.txt
  Finacial Domain/Stock Market Data Scrapper/ticker.json
  Finacial Domain/Stock Market Data Scrapper/webapp_scrapper.mp4
Labels: GSSOC24, gssoc, level3

#414 Stock Market Turnover Ratio Dataset Analysis
  Finacial Domain/Stock Turnover Ratio Dataset Analysis/DDEM01USA156NWDB.csv
  Finacial Domain/Stock Turnover Ratio Dataset Analysis/StockTurnoverRatio.ipynb
  Finacial Domain/Stock Turnover Ratio Dataset Analysis/requirement.txt
Labels: GSSOC24, gssoc, level2

#415 Uniqlo Stock Price Prediction
  Tokyo Stock Exchange/Uniqlo Stock Price Dataset Analysis/Dataset/Uniqlo(FastRetailing) 2012-2016 Training - stocks2012-2016.csv
  Tokyo Stock Exchange/Uniqlo Stock Price Dataset Analysis/Dataset/Uniqlo(FastRetailing) 2017 Test - stocks2017.csv
  Tokyo Stock Exchange/Uniqlo Stock Price Dataset Analysis/UniqloStock.ipynb
  Tokyo Stock Exchange/Uniqlo Stock Price Dataset Analysis/requirement.txt
  Tokyo Stock Exchange/Uniqlo Stock Price Dataset Analysis/uniqlo_stock_prediction_model.h5
Labels: GSSOC24, gssoc, level2

#430 Add Credit Card Fraud Detection
  Credit Card Fraud Detection/Credit Card Fraud Detection using ML/Credit_Card_Fraud_Detection_using_Machine_Learning.ipynb
  Credit Card Fraud Detection/Credit Card Fraud Detection using ML/README.md
Labels: GSSOC24, gssoc, level2

#432 Istanbul Stock Exchange
  Istanbul Stock Exchange/IstanbulStockExchange.ipynb
  Istanbul Stock Exchange/istanbul_stock_exchange.csv
  Istanbul Stock Exchange/requirement.txt
Labels: GSSOC24, gssoc, level2

#433 Add Nifty lstm analysis
  Nifty /Nifty LSTM analysis/NIFTY_50_Stock_Market_Data_(2000_2021)_using_RNN.ipynb
  Nifty /Nifty LSTM analysis/README.md
  Nifty /Nifty LSTM analysis/Stock_Market_Prediction_Using_LSTM.ipynb
  Nifty /Nifty LSTM analysis/Stock_Price_Prediction_using_ML.ipynb
Labels: GSSOC24, gssoc, level2
